name = "UnbalancedHaarWavelet"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["UnbalancedHaarWavelet"]
 

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

 

[[require]]
name = "LaminarFamiliesMaximalBinaryTrees"
git = "https://github.com/SmaniaD/LaminarFamiliesMaximalBinaryTrees.git"
rev = "main"

[[require]]
name = "Burkholder"
git = "https://github.com/SmaniaD/Burkholder.git"
rev = "main"

[[lean_lib]]
name = "UnbalancedHaarWavelet"

[[require]]
name = "mathlib"
scope = "leanprover-community"
