name = "UnbalancedHaarWavelet"
version = "0.1.1"
keywords = ["math"]
defaultTargets = ["UnbalancedHaarWavelet"]
 

releaseRepo = "https://github.com/SmaniaD/UnbalancedHaarWavelet"
preferReleaseBuild = true

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "LaminarFamiliesMaximalBinaryTrees"
git = "https://github.com/SmaniaD/LaminarFamiliesMaximalBinaryTrees.git"
rev = "v0.1.0"

[[require]]
name = "Burkholder"
git = "https://github.com/SmaniaD/Burkholder.git"
rev = "v0.1.0"

[[require]]
name = "UnconditionalSchauderBasis"
git = "https://github.com/SmaniaD/UnconditionalSchauderBasis.git"
rev = "v0.1.0"

[[lean_lib]]
name = "UnbalancedHaarWavelet"

[[require]]
name = "mathlib"
scope = "leanprover-community"
