import UnbalancedHaarWavelet.Basic
import LaminarFamiliesMaximalBinaryTrees
import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.MeasureTheory.Function.AEEqOfIntegral

namespace UnbalancedHaarWavelet

variable {α : Type*} [MeasurableSpace α]

/-- A nested sequence of finite partitions of a measurable space -/
structure NestedFinitePartitionSequence where
  /-- Partitions indexed by natural numbers -/
  partitions : ℕ → Finset (Set α)
  /-- The first partition has exactly one element. -/
  first_partition_card_one : (partitions 0).card = 1
  /-- The unique element of the first partition is `α` (i.e. `Set.univ`). -/
  first_partition_eq_univ : partitions 0 = {Set.univ}
  /-- Each part is measurable -/
  measurable : ∀ n s, s ∈ partitions n → MeasurableSet s
  /-- every element of partition n+1 is contained in an element of the partition n -/
  nested : ∀ n s, s ∈ partitions (n + 1) → ∃ t, t ∈ partitions n ∧ s ⊆ t
  /-- father  is union of its children -/
  covering_father : ∀ n s, s ∈ partitions n → s ⊆ ⋃ t ∈ partitions (n + 1), t
  /-- Parts are pairwise disjoint -/
  disjoint : ∀ n s t, s ∈ partitions n → t ∈ partitions n → s ≠ t → Disjoint s t
  /-- Parts cover the space -/
  covering : ∀ n, (⋃ s ∈ partitions n, s) = Set.univ
  /-- The sigma algebra generated by the union of partitions -/
  generates : (⨆ n, MeasurableSpace.generateFrom (partitions n)) = ‹MeasurableSpace α›


/-- A measure space with a **good grid**: a σ-finite measure μ of finite total mass together
    with a nested sequence of finite partitions, and constants 0 < λ₁ ≤ λ₂ < 1 such that
    for every cell `s` at level `n + 1` contained in its parent cell `t` at level `n`,
    $$\lambda_1 \cdot \mu(t) \;\le\; \mu(s) \;\le\; \lambda_2 \cdot \mu(t).$$ -/
structure GoodGrid where
  /-- The measure on α -/
  μ : MeasureTheory.Measure α
  /-- The total mass is finite -/
  isFinite : MeasureTheory.IsFiniteMeasure μ
  /-- The nested sequence of finite partitions forming the grid -/
  grid : NestedFinitePartitionSequence (α := α)
  /-- Every elements of the partition has positive measure -/
  positive_measure : ∀ n s, s ∈ grid.partitions n → μ s > 0
  /-- Lower ratio bound (positive) -/
  lambda1 : ℝ
  /-- Upper ratio bound (strictly less than 1) -/
  lambda2 : ℝ
  /-- λ₁ is strictly positive -/
  hlambda1_pos : 0 < lambda1
  /-- λ₂ is strictly less than 1 -/
  hlambda2_lt_one : lambda2 < 1
  /-- λ₁ ≤ λ₂ -/
  hlambda1_le_lambda2 : lambda1 ≤ lambda2
  /-- Each child cell's measure is at least λ₁ times its parent's measure -/
  ratio_lower : ∀ (n : ℕ) (s t : Set α),
      s ∈ grid.partitions (n + 1) → t ∈ grid.partitions n → s ⊆ t →
      ENNReal.ofReal lambda1 * μ t ≤ μ s
  /-- Each child cell's measure is at most λ₂ times its parent's measure -/
  ratio_upper : ∀ (n : ℕ) (s t : Set α),
      s ∈ grid.partitions (n + 1) → t ∈ grid.partitions n → s ⊆ t →
      μ s ≤ ENNReal.ofReal lambda2 * μ t



/-- Children of a cell `Q` at level `n`: cells in level `n+1` contained in `Q`. -/
def GoodGrid.children (G : GoodGrid (α := α)) (n : ℕ) (Q : Set α) : Set (Set α) :=
    {s | s ∈ G.grid.partitions (n + 1) ∧ s ⊆ Q}

/-- Finset version of `GoodGrid.children`, obtained by filtering the next partition. -/
noncomputable def GoodGrid.childrenFinset
    (G : GoodGrid (α := α)) (n : ℕ) (Q : Set α) : Finset (Set α) :=
    by
        classical
        exact (G.grid.partitions (n + 1)).filter (fun s => s ⊆ Q)

lemma GoodGrid.mem_childrenFinset_iff (G : GoodGrid (α := α)) (n : ℕ) (Q s : Set α) :
        s ∈ G.childrenFinset n Q ↔ s ∈ G.children n Q := by
    classical
    simp [GoodGrid.childrenFinset, GoodGrid.children]

lemma NestedFinitePartitionSequence.nested_iterate
    (S : NestedFinitePartitionSequence (α := α))
    (n k : ℕ) (s : Set α) (hs : s ∈ S.partitions (n + k)) :
    ∃ t, t ∈ S.partitions n ∧ s ⊆ t := by
  induction k generalizing n s with
  | zero =>
      exact ⟨s, by simpa using hs, Set.Subset.rfl⟩
  | succ k ih =>
      have hs' : s ∈ S.partitions ((n + k) + 1) := by
        simpa [Nat.add_assoc] using hs
      obtain ⟨u, hu, hsu⟩ := S.nested (n + k) s hs'
      obtain ⟨t, ht, hut⟩ := ih n u hu
      exact ⟨t, ht, hsu.trans hut⟩

lemma GoodGrid.partition_nonempty
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (n : ℕ) (Q : Set α) (hQ : Q ∈ G.grid.partitions n) :
    Q.Nonempty := by
  by_contra hQ_empty
  simp only [Set.not_nonempty_iff_eq_empty] at hQ_empty
  have hμ0 : G.μ Q = 0 := by simp [hQ_empty]
  have hμpos : 0 < G.μ Q := G.positive_measure n Q hQ
  rw [hμ0] at hμpos
  exact absurd hμpos (lt_irrefl 0)

lemma GoodGrid.partition_subset_or_disjoint_of_le
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (n m : ℕ) (hnm : n ≤ m)
    (Q : Set α) (hQ : Q ∈ G.grid.partitions n)
    (P : Set α) (hP : P ∈ G.grid.partitions m) :
    P ⊆ Q ∨ Disjoint P Q := by
  have hP' : P ∈ G.grid.partitions (n + (m - n)) := by
    simpa [Nat.add_sub_of_le hnm] using hP
  obtain ⟨t, ht, hPt⟩ := G.grid.nested_iterate n (m - n) P hP'
  by_cases htQ : t = Q
  · left
    simpa [htQ] using hPt
  · right
    have htQ_disj : Disjoint t Q := G.grid.disjoint n t Q ht hQ htQ
    exact htQ_disj.mono_left hPt

lemma GoodGrid.exists_child_containing_of_lt
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (n m : ℕ) (hnm : n < m)
    (Q : Set α) (hQ : Q ∈ G.grid.partitions n)
    (P : Set α) (hP : P ∈ G.grid.partitions m)
    (hPQ : P ⊆ Q) :
    ∃ c, c ∈ G.children n Q ∧ P ⊆ c := by
  have hn1m : n + 1 ≤ m := by omega
  have hP' : P ∈ G.grid.partitions ((n + 1) + (m - (n + 1))) := by
    simpa [Nat.add_sub_of_le hn1m] using hP
  obtain ⟨c, hc, hPc⟩ := G.grid.nested_iterate (n + 1) (m - (n + 1)) P hP'
  obtain ⟨t, ht, hct⟩ := G.grid.nested n c hc
  have htQ : t = Q := by
    by_contra htQ_ne
    have htQ_disj : Disjoint t Q := G.grid.disjoint n t Q ht hQ htQ_ne
    obtain ⟨x, hxP⟩ := G.partition_nonempty m P hP
    have hx_t : x ∈ t := hct (hPc hxP)
    have hx_Q : x ∈ Q := hPQ hxP
    exact (Set.disjoint_left.mp htQ_disj hx_t hx_Q).elim
  refine ⟨c, ?_, hPc⟩
  exact ⟨hc, by simpa [htQ] using hct⟩


structure BinaryRefinementOfGoodGrid (G : GoodGrid (α := α)) [DecidableEq (Set α)] where
  tree : ∀ n (Q : Set α), Q ∈ G.grid.partitions n → BinaryTreeWithRootandTops (Set α)
  childs_are_children : ∀ n (Q : Set α) (hQ : Q ∈ G.grid.partitions n) (s : Set α),
      s ∈ (tree n Q hQ).Childs ↔ s ∈ G.children n Q
  tops_are_children : ∀ n (Q : Set α) (hQ : Q ∈ G.grid.partitions n) (s : Set α),
      s ∈ (tree n Q hQ).Tops ↔ s ∈ G.children n Q
  root_contains_children : ∀ n (Q : Set α) (hQ : Q ∈ G.grid.partitions n) (s : Set α),
      s ∈ G.children n Q → s ∈ Combinatorial_Support (tree n Q hQ).Root

/-- If a natural number is `< 2`, then it is either `0` or `1`. -/
lemma card_lt_two_eq_zero_or_one (k : ℕ) (hk : k < 2) : k = 0 ∨ k = 1 := by
  interval_cases k <;> simp_all

/-- Every cell in a GoodGrid has at least one child in the next partition. -/
theorem GoodGrid.children_card_ge_one
    (G : GoodGrid (α := α)) [DecidableEq (Set α)] (n : ℕ) (Q : Set α)
    (hQ : Q ∈ G.grid.partitions n) :
    (G.childrenFinset n Q).card ≥ 1 := by
  classical
  by_contra h
  push_neg at h
  have h_card_zero : (G.childrenFinset n Q).card = 0 := by omega
  have h_empty : (G.childrenFinset n Q) = ∅ := Finset.card_eq_zero.mp h_card_zero
  -- By covering_father, Q is covered by the next partition level
  have h_covered : Q ⊆ ⋃ s ∈ G.grid.partitions (n + 1), s :=
    G.grid.covering_father n Q hQ
  -- Q must be nonempty (it's a partition element of a covering)
  have hQ_nonempty : Q.Nonempty := by
    by_contra h
    simp only [Set.not_nonempty_iff_eq_empty] at h
    have hμ0 : G.μ Q = 0 := by simp [h]
    have hμpos : 0 < G.μ Q := G.positive_measure n Q hQ
    rw [hμ0] at hμpos
    exact absurd hμpos (lt_irrefl 0)
  obtain ⟨x, hxQ⟩ := hQ_nonempty
  -- x is in some element of partition (n+1) by covering_father
  have hx_in_union : x ∈ ⋃ s ∈ G.grid.partitions (n + 1), s := h_covered hxQ
  simp only [Set.mem_iUnion, exists_prop] at hx_in_union
  obtain ⟨s, hs, hxs⟩ := hx_in_union
  -- By nested property, s is contained in some element t of partition n
  obtain ⟨t, ht, hs_sub_t⟩ := G.grid.nested n s hs
  -- Q and t are both in partition n. Since x ∈ Q and x ∈ s ⊆ t, we have Q = t
  have h_Q_eq_t : Q = t := by
    -- If Q ≠ t, they're disjoint by the disjoint property
    by_contra h_ne
    have h_disj : Disjoint (Q : Set α) (t : Set α) :=
      G.grid.disjoint n Q t hQ ht h_ne
    -- But x ∈ Q ∩ t, contradiction
    have hx_inter : x ∈ Q ∩ t := ⟨hxQ, hs_sub_t hxs⟩
    -- Disjoint means Q ⊓ t ≤ ⊥, which for sets means Q ∩ t ⊆ ∅
    have h_empty_inter : Q ∩ t ⊆ (∅ : Set α) := by
      have : (Q : Set α) ⊓ (t : Set α) = (⊥ : Set α) :=
        disjoint_iff.mp h_disj
      simpa [Set.le_eq_subset, Set.inf_eq_inter, Set.bot_eq_empty]
    have : x ∈ (∅ : Set α) := h_empty_inter hx_inter
    exact this.elim
  -- Therefore s ⊆ Q, so s is a child of Q
  have hs_sub_Q : s ⊆ Q := by rw [h_Q_eq_t]; exact hs_sub_t
  have hs_child : s ∈ G.childrenFinset n Q := by
    simp only [GoodGrid.childrenFinset, Finset.mem_filter, hs, hs_sub_Q, and_true]
  -- This contradicts the empty assumption
  simp only [h_empty, Finset.notMem_empty] at hs_child




/-- If a cell does not have at least two children, then its children cardinal is `0` or `1`. -/
theorem GoodGrid.children_card_cases_zero_or_one
    (G : GoodGrid (α := α)) [DecidableEq (Set α)] (n : ℕ) (Q : Set α)
    (h_not_ge_two : ¬ (G.childrenFinset n Q).card ≥ 2) :
    (G.childrenFinset n Q).card = 0 ∨ (G.childrenFinset n Q).card = 1 := by
  have hlt : (G.childrenFinset n Q).card < 2 := by omega
  exact card_lt_two_eq_zero_or_one _ hlt

/-- If `card(children) < 2`, then in fact `card(children) = 1` (never `0`). -/
theorem GoodGrid.children_card_eq_one_of_not_ge_two
    (G : GoodGrid (α := α)) [DecidableEq (Set α)] (n : ℕ) (Q : Set α)
    (hQ : Q ∈ G.grid.partitions n)
    (h_not_ge_two : ¬ (G.childrenFinset n Q).card ≥ 2) :
    (G.childrenFinset n Q).card = 1 := by
  have h_cases :
      (G.childrenFinset n Q).card = 0 ∨ (G.childrenFinset n Q).card = 1 :=
    G.children_card_cases_zero_or_one n Q h_not_ge_two
  rcases h_cases with h_zero | h_one
  · have h_ge_one : (G.childrenFinset n Q).card ≥ 1 := G.children_card_ge_one n Q hQ
    omega
  · exact h_one


/-- Every point of a partition cell belongs to one of its children. -/
theorem GoodGrid.covering_by_children
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (n : ℕ) (Q : Set α) (hQ : Q ∈ G.grid.partitions n) :
    Q ⊆ ⋃ s ∈ G.children n Q, s := by
  intro x hxQ
  have hx_in_union : x ∈ ⋃ s ∈ G.grid.partitions (n + 1), s :=
    G.grid.covering_father n Q hQ hxQ
  simp only [Set.mem_iUnion, exists_prop] at hx_in_union
  obtain ⟨s, hs, hxs⟩ := hx_in_union
  obtain ⟨t, ht, hs_sub_t⟩ := G.grid.nested n s hs
  have h_Q_eq_t : Q = t := by
    by_contra h_ne
    have h_disj : Disjoint (Q : Set α) (t : Set α) :=
      G.grid.disjoint n Q t hQ ht h_ne
    have hx_inter : x ∈ Q ∩ t := ⟨hxQ, hs_sub_t hxs⟩
    have h_empty_inter : Q ∩ t ⊆ (∅ : Set α) := by
      have : (Q : Set α) ⊓ (t : Set α) = (⊥ : Set α) :=
        disjoint_iff.mp h_disj
      simpa [Set.le_eq_subset, Set.inf_eq_inter, Set.bot_eq_empty]
    exact (h_empty_inter hx_inter).elim
  have hs_sub_Q : s ⊆ Q := by
    rw [h_Q_eq_t]
    exact hs_sub_t
  have hs_child : s ∈ G.children n Q := ⟨hs, hs_sub_Q⟩
  exact Set.mem_iUnion.2 ⟨s, Set.mem_iUnion.2 ⟨hs_child, hxs⟩⟩


/-- If `Q` has exactly one child and children cover `Q`, then `Q` equals its only child. -/
theorem GoodGrid.eq_only_child_of_children_card_eq_one
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (n : ℕ) (Q : Set α)
    (hcard : (G.childrenFinset n Q).card = 1)
    (hQ : Q ∈ G.grid.partitions n) :
    ∃ s : Set α, s ∈ G.children n Q ∧ Q = s := by
  classical
  obtain ⟨s, hs_singleton⟩ := Finset.card_eq_one.mp hcard
  have hs_mem_finset : s ∈ G.childrenFinset n Q := by
    rw [hs_singleton]
    simp
  have hs_mem_child : s ∈ G.children n Q := (G.mem_childrenFinset_iff n Q s).1 hs_mem_finset
  have hs_sub_Q : s ⊆ Q := hs_mem_child.2
  have h_unique : ∀ t : Set α, t ∈ G.children n Q → t = s := by
    intro t ht_child
    have ht_fin : t ∈ G.childrenFinset n Q := (G.mem_childrenFinset_iff n Q t).2 ht_child
    have ht_single : t ∈ ({s} : Finset (Set α)) := by
      simpa [hs_singleton] using ht_fin
    simpa using ht_single
  have hQ_sub_s : Q ⊆ s := by
    intro x hxQ
    have hx_union : x ∈ ⋃ t ∈ G.children n Q, t :=
      G.covering_by_children n Q hQ hxQ
    rcases by simpa using hx_union with ⟨t, ht_child, hx_t⟩
    have ht_eq_s : t = s := h_unique t ht_child
    simpa [ht_eq_s] using hx_t
  refine ⟨s, hs_mem_child, Set.Subset.antisymm hQ_sub_s hs_sub_Q⟩

/-- Having exactly one child is impossible for a cell in a GoodGrid,
    because of the measure ratio bounds. -/
theorem GoodGrid.not_children_card_eq_one
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (n : ℕ) (Q : Set α) (hQ : Q ∈ G.grid.partitions n)
  :
    ¬ (G.childrenFinset n Q).card = 1 := by
  classical
  intro hcard
  obtain ⟨s, hs_child, hQ_eq_s⟩ :=
    G.eq_only_child_of_children_card_eq_one n Q hcard hQ
  have hs_part : s ∈ G.grid.partitions (n + 1) := hs_child.1
  have hs_sub : s ⊆ Q := hs_child.2

  have hμQ_le : G.μ Q ≤ ENNReal.ofReal G.lambda2 * G.μ Q := by
    have htmp : G.μ s ≤ ENNReal.ofReal G.lambda2 * G.μ Q :=
      G.ratio_upper n s Q hs_part hQ hs_sub
    simpa [hQ_eq_s] using htmp

  have hμQ_pos : 0 < G.μ Q := G.positive_measure n Q hQ
  have hμQ_ne_zero : G.μ Q ≠ 0 := ne_of_gt hμQ_pos

  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  have hμQ_lt_top : G.μ Q < ⊤ := by
    exact MeasureTheory.measure_lt_top (μ := G.μ) Q
  have h_rhs_lt_top : ENNReal.ofReal G.lambda2 * G.μ Q < ⊤ := by
    exact ENNReal.mul_lt_top (by simp) hμQ_lt_top

  have hμQ_le_real :
      (G.μ Q).toReal ≤ (ENNReal.ofReal G.lambda2 * G.μ Q).toReal :=
    (ENNReal.toReal_le_toReal hμQ_lt_top.ne h_rhs_lt_top.ne).2 hμQ_le

  have hlambda2_nonneg : 0 ≤ G.lambda2 := by
    exact le_trans (le_of_lt G.hlambda1_pos) G.hlambda1_le_lambda2

  have hμQ_le_real' : (G.μ Q).toReal ≤ G.lambda2 * (G.μ Q).toReal := by
    simpa [ENNReal.toReal_mul, ENNReal.toReal_ofReal, hlambda2_nonneg, hμQ_lt_top.ne]
      using hμQ_le_real

  have hμQ_toReal_pos : 0 < (G.μ Q).toReal :=
    ENNReal.toReal_pos hμQ_ne_zero hμQ_lt_top.ne

  have h_one_le_lambda2 : 1 ≤ G.lambda2 := by
    nlinarith [hμQ_le_real', hμQ_toReal_pos]

  linarith [h_one_le_lambda2, G.hlambda2_lt_one]

/-- Conclusion: every partition element has at least two children,
    assuming children cover each parent cell. -/
theorem GoodGrid.all_partition_elements_have_two_children
    (G : GoodGrid (α := α)) [DecidableEq (Set α)] :
    ∀ n (Q : Set α), Q ∈ G.grid.partitions n → (G.childrenFinset n Q).card ≥ 2 := by
  intro n Q hQ
  by_contra h_not_ge_two
  have hcard1 : (G.childrenFinset n Q).card = 1 :=
    G.children_card_eq_one_of_not_ge_two n Q hQ h_not_ge_two
  have hnot1 : ¬ (G.childrenFinset n Q).card = 1 :=
    G.not_children_card_eq_one n Q hQ
  exact hnot1 hcard1




/-- Existence of binary refinements of a good grid for any GoodGrid. -/
theorem exists_binaryRefinementOfGoodGrid
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    : Nonempty (BinaryRefinementOfGoodGrid (G := G)) := by
  classical
  have hTree :
      ∀ n (Q : Set α) (hQ : Q ∈ G.grid.partitions n),
        ∃ T : BinaryTreeWithRootandTops (Set α),
          T.Childs = G.childrenFinset n Q ∧ T.Tops = G.childrenFinset n Q := by
    intro n Q hQ
    rcases exists_tree_childs_eq_C_and_all_childs_in_Tops_of_card_ge_two
        (C := G.childrenFinset n Q)
        (GoodGrid.all_partition_elements_have_two_children G n Q hQ) with ⟨T, hChilds, hTops⟩
    exact ⟨T, hChilds, hTops.symm⟩

  choose tree hChilds hTops using hTree

  refine ⟨{
    tree := tree
    childs_are_children := ?_
    tops_are_children := ?_
    root_contains_children := ?_
  }⟩
  · intro n Q hQ s
    simpa [hChilds n Q hQ] using (G.mem_childrenFinset_iff n Q s)
  · intro n Q hQ s
    simpa [hTops n Q hQ] using (G.mem_childrenFinset_iff n Q s)
  · intro n Q hQ s hs
    have hs_child : s ∈ (tree n Q hQ).Childs := by
      simpa [hChilds n Q hQ] using (G.mem_childrenFinset_iff n Q s).2 hs
    exact (tree n Q hQ).RootcontainsChilds hs_child

/-- Support associated with a branch side `A`: union of the cells in `A`. -/
def branchSupport (A : Finset (Set α)) : Set α :=
  ⋃ s ∈ (A : Set (Set α)), s

omit [MeasurableSpace α] in
lemma branchSupport_mono {A B : Finset (Set α)} (hAB : A ⊆ B) :
    branchSupport A ⊆ branchSupport B := by
  intro x hx
  rcases (by simpa [branchSupport] using hx) with ⟨s, hsA, hxs⟩
  have hsB : s ∈ B := hAB hsA
  exact by
    simpa [branchSupport] using (show x ∈ ⋃ t ∈ (B : Set (Set α)), t from
      Set.mem_iUnion.2 ⟨s, Set.mem_iUnion.2 ⟨hsB, hxs⟩⟩)

lemma disjoint_branchSupport_of_finset_disjoint
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (n : ℕ) (A B : Finset (Set α))
    (hA_part : ∀ s, s ∈ A → s ∈ G.grid.partitions (n + 1))
    (hB_part : ∀ s, s ∈ B → s ∈ G.grid.partitions (n + 1))
    (hAB : Disjoint A B) :
    Disjoint (branchSupport A) (branchSupport B) := by
  refine Set.disjoint_left.2 ?_
  intro x hxA hxB
  rcases (by simpa [branchSupport] using hxA) with ⟨s, hsA, hxs⟩
  rcases (by simpa [branchSupport] using hxB) with ⟨t, htB, hxt⟩
  have hst_ne : s ≠ t := by
    intro hst
    have hs_not_mem_B : s ∉ B := (Finset.disjoint_left.mp hAB) hsA
    exact hs_not_mem_B (hst ▸ htB)
  have hst_disj : Disjoint s t :=
    G.grid.disjoint (n + 1) s t (hA_part s hsA) (hB_part t htB) hst_ne
  exact (Set.disjoint_left.mp hst_disj hxs hxt).elim

omit [MeasurableSpace α] in
lemma subset_branchSupport_of_mem {A : Finset (Set α)} {s : Set α}
    (hs : s ∈ A) : s ⊆ branchSupport A := by
  intro x hx
  exact by
    simpa [branchSupport] using
      (show x ∈ ⋃ t ∈ (A : Set (Set α)), t from
        Set.mem_iUnion.2 ⟨s, Set.mem_iUnion.2 ⟨hs, hx⟩⟩)

lemma measurableSet_branchSupport_of_partition
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (n : ℕ) (A : Finset (Set α))
    (hA_part : ∀ s, s ∈ A → s ∈ G.grid.partitions (n + 1)) :
    MeasurableSet (branchSupport A) := by
  classical
  induction A using Finset.induction_on with
  | empty =>
      simp [branchSupport]
  | @insert a A ha ih =>
    have ha_part : a ∈ G.grid.partitions (n + 1) := hA_part a (by simp [ha])
    have ha_meas : MeasurableSet a := G.grid.measurable (n + 1) a ha_part
    have hA_part' : ∀ s, s ∈ A → s ∈ G.grid.partitions (n + 1) := by
      intro s hs
      exact hA_part s (by simp [hs])
    have hA_meas' : MeasurableSet (branchSupport A) := ih hA_part'
    have h_union : branchSupport (insert a A) = a ∪ branchSupport A := by
      ext x
      constructor
      · intro hx
        simp only [branchSupport, Set.mem_iUnion] at hx
        rcases hx with ⟨s, hs, hxs⟩
        rcases (Finset.mem_insert.mp hs) with rfl | hsA
        · exact Or.inl hxs
        · exact Or.inr (by
            simpa [branchSupport] using
              (show x ∈ ⋃ t ∈ (A : Set (Set α)), t from
                Set.mem_iUnion.2 ⟨s, Set.mem_iUnion.2 ⟨hsA, hxs⟩⟩))
      · intro hx
        rcases hx with hxa | hxA
        · simpa [branchSupport] using
            (show x ∈ ⋃ t ∈ ((insert a A : Finset (Set α)) : Set (Set α)), t from
              Set.mem_iUnion.2 ⟨a, Set.mem_iUnion.2 ⟨by simp, hxa⟩⟩)
        · rcases (by simpa [branchSupport] using hxA) with ⟨s, hsA, hxs⟩
          simpa [branchSupport] using
            (show x ∈ ⋃ t ∈ ((insert a A : Finset (Set α)) : Set (Set α)), t from
              Set.mem_iUnion.2 ⟨s, Set.mem_iUnion.2 ⟨by simp [hsA], hxs⟩⟩)
    rw [h_union]
    exact ha_meas.union hA_meas'

lemma measure_branchSupport_pos_of_nonempty
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
  (A : Finset (Set α))
    (hA_pos_cells : ∀ s, s ∈ A → 0 < G.μ s)
    (hA_nonempty : A.Nonempty) :
    0 < G.μ (branchSupport A) := by
  obtain ⟨s, hs⟩ := hA_nonempty
  have hs_sub : s ⊆ branchSupport A := subset_branchSupport_of_mem hs
  have hμs_pos : 0 < G.μ s := hA_pos_cells s hs
  have hμs_le : G.μ s ≤ G.μ (branchSupport A) := MeasureTheory.measure_mono hs_sub
  exact lt_of_lt_of_le hμs_pos hμs_le

/-- Haar wavelet associated with a branch split `(A, B)`:
`1_{S_A} / μ(S_A) - 1_{S_B} / μ(S_B)`. -/
noncomputable def haarWavelet
    (μ : MeasureTheory.Measure α) (A B : Set α) : α → ℝ :=
  fun x =>
    Set.indicator A
      (fun _ => 1 / (μ A).toReal) x
    -
    Set.indicator B
      (fun _ => 1 / (μ B).toReal) x

/-- Orthogonality of two Haar wavelets when the four supports are pairwise disjoint
across the two wavelets. -/
theorem integral_mul_haarWavelet_eq_zero_of_disjoint
    (μ : MeasureTheory.Measure α)
    (A B C D : Set α)
    (hAC : Disjoint A C)
    (hAD : Disjoint A D)
    (hBC : Disjoint B C)
    (hBD : Disjoint B D) :
    ∫ x, haarWavelet μ A B x * haarWavelet μ C D x ∂ μ = 0 := by
  have hAC' := Set.disjoint_left.mp hAC
  have hAD' := Set.disjoint_left.mp hAD
  have hBC' := Set.disjoint_left.mp hBC
  have hBD' := Set.disjoint_left.mp hBD
  have hpointwise :
      ∀ x,
        haarWavelet μ A B x * haarWavelet μ C D x = 0 := by
    intro x
    set iA : ℝ :=
      Set.indicator A
        (fun _ => 1 / (μ A).toReal) x
    set iB : ℝ :=
      Set.indicator B
        (fun _ => 1 / (μ B).toReal) x
    set iC : ℝ :=
      Set.indicator C
        (fun _ => 1 / (μ C).toReal) x
    set iD : ℝ :=
      Set.indicator D
        (fun _ => 1 / (μ D).toReal) x
    have hiAC : iA * iC = 0 := by
      by_cases hxA : x ∈ A
      · have hxC : x ∉ C := by
          intro hxC
          exact (hAC' hxA hxC).elim
        simp [iA, iC, hxA, hxC]
      · simp [iA, hxA]
    have hiAD : iA * iD = 0 := by
      by_cases hxA : x ∈ A
      · have hxD : x ∉ D := by
          intro hxD
          exact (hAD' hxA hxD).elim
        simp [iA, iD, hxA, hxD]
      · simp [iA, hxA]
    have hiBC : iB * iC = 0 := by
      by_cases hxB : x ∈ B
      · have hxC : x ∉ C := by
          intro hxC
          exact (hBC' hxB hxC).elim
        simp [iB, iC, hxB, hxC]
      · simp [iB, hxB]
    have hiBD : iB * iD = 0 := by
      by_cases hxB : x ∈ B
      · have hxD : x ∉ D := by
          intro hxD
          exact (hBD' hxB hxD).elim
        simp [iB, iD, hxB, hxD]
      · simp [iB, hxB]
    calc
      haarWavelet μ A B x * haarWavelet μ C D x
          = (iA - iB) * (iC - iD) := by simp [haarWavelet, iA, iB, iC, iD]
      _ = iA * iC - iA * iD - iB * iC + iB * iD := by ring
      _ = 0 := by simp [hiAC, hiAD, hiBC, hiBD]
  have hfun :
      (fun x => haarWavelet μ A B x * haarWavelet μ C D x)
        = fun _ => (0 : ℝ) := by
    funext x
    exact hpointwise x
  rw [hfun]
  simp

/-- The Haar wavelet `ψ_{A,B}` has zero mean under positivity assumptions. -/
theorem integral_haarWavelet_eq_zero_of_pos
    (μ : MeasureTheory.Measure α) [MeasureTheory.IsFiniteMeasure μ]
    (A B : Set α)
    (hAB : Disjoint A B)
    (hA_meas : MeasurableSet A)
    (hB_meas : MeasurableSet B)
    (hA_pos : 0 < μ A)
    (hB_pos : 0 < μ B) :
    ∫ x, haarWavelet μ A B x ∂μ = 0 := by
  let _ := hAB
  have hA_ne_zero : μ A ≠ 0 := ne_of_gt hA_pos
  have hB_ne_zero : μ B ≠ 0 := ne_of_gt hB_pos
  have hA_lt_top : μ A < ⊤ :=
    MeasureTheory.measure_lt_top (μ := μ) A
  have hB_lt_top : μ B < ⊤ :=
    MeasureTheory.measure_lt_top (μ := μ) B
  have hA_toReal_ne_zero : (μ A).toReal ≠ 0 :=
    ne_of_gt (ENNReal.toReal_pos hA_ne_zero hA_lt_top.ne)
  have hB_toReal_ne_zero : (μ B).toReal ≠ 0 :=
    ne_of_gt (ENNReal.toReal_pos hB_ne_zero hB_lt_top.ne)
  have hIntA :
      MeasureTheory.Integrable
        (fun x =>
          Set.indicator A
            (fun _ => 1 / (μ A).toReal) x) μ := by
    exact (MeasureTheory.integrable_const
      (1 / (μ A).toReal)).indicator hA_meas
  have hIntB :
      MeasureTheory.Integrable
        (fun x =>
          Set.indicator B
            (fun _ => 1 / (μ B).toReal) x) μ := by
    exact (MeasureTheory.integrable_const
      (1 / (μ B).toReal)).indicator hB_meas
  calc
    ∫ x, haarWavelet μ A B x ∂μ
        = ∫ x,
            Set.indicator A
              (fun _ => 1 / (μ A).toReal) x
            -
            Set.indicator B
              (fun _ => 1 / (μ B).toReal) x ∂μ := by
          simp [haarWavelet]
    _ =
        (∫ x,
          Set.indicator A
            (fun _ => 1 / (μ A).toReal) x ∂μ)
        -
        (∫ x,
          Set.indicator B
            (fun _ => 1 / (μ B).toReal) x ∂μ) := by
          exact MeasureTheory.integral_sub hIntA hIntB
    _ =
        μ.real A * (μ A).toReal⁻¹
        -
        (μ.real B * (μ B).toReal⁻¹) := by
      simp [hA_meas, hB_meas]
    _ = 1 - 1 := by
      change
        (μ A).toReal * (μ A).toReal⁻¹
          -
          ((μ B).toReal * (μ B).toReal⁻¹)
          = 1 - 1
      field_simp [hA_toReal_ne_zero, hB_toReal_ne_zero]
    _ = 0 := by ring



/-- Orthogonality when `S_A ∪ S_B ⊆ S_C`, `S_C ⟂ S_D`, and `ψ_{A,B}` has zero mean. -/
theorem integral_mul_haarWavelet_eq_zero_of_subset_left
    (μ : MeasureTheory.Measure α) [MeasureTheory.IsFiniteMeasure μ]
    (A B C D : Set α)
    (hAB : Disjoint A B)
    (hCD : Disjoint C D)
    (hsub : A ∪ B ⊆ C)
    (hA_meas : MeasurableSet A)
    (hB_meas : MeasurableSet B)
    (hA_pos : 0 < μ A)
    (hB_pos : 0 < μ B)
    :
    ∫ x, haarWavelet μ A B x * haarWavelet μ C D x ∂ μ = 0 := by
  have hmean_zero : ∫ x, haarWavelet μ A B x ∂μ = 0 := by
    exact integral_haarWavelet_eq_zero_of_pos
      μ A B hAB hA_meas hB_meas hA_pos hB_pos
  let cC : ℝ := 1 / (μ C).toReal
  have hCD' := Set.disjoint_left.mp hCD
  let _ := hAB
  have hmul_eq :
      (fun x => haarWavelet μ A B x * haarWavelet μ C D x)
        = fun x => cC * haarWavelet μ A B x := by
    funext x
    by_cases hxU : x ∈ A ∪ B
    · have hxC : x ∈ C := hsub hxU
      have hxD : x ∉ D := by
        intro hxD
        exact (hCD' hxC hxD).elim
      simp [haarWavelet, cC, hxC, hxD, mul_comm]
    · have hxA : x ∉ A := by
        intro hxA
        exact hxU (Or.inl hxA)
      have hxB : x ∉ B := by
        intro hxB
        exact hxU (Or.inr hxB)
      simp [haarWavelet, hxA, hxB]
  rw [hmul_eq, MeasureTheory.integral_const_mul, hmean_zero]
  simp

theorem integral_mul_haarWavelet_eq_zero_of_subset_right
    (μ : MeasureTheory.Measure α) [MeasureTheory.IsFiniteMeasure μ]
    (A B C D : Set α)
    (hAB : Disjoint A B)
    (hCD : Disjoint C D)
  (hsub : A ∪ B ⊆ D)
  (hC_meas : MeasurableSet C)
    (hA_meas : MeasurableSet A)
    (hB_meas : MeasurableSet B)
    (hA_pos : 0 < μ A)
    (hB_pos : 0 < μ B) :
    ∫ x, haarWavelet μ A B x * haarWavelet μ C D x ∂ μ = 0 := by
  have hmean_zero : ∫ x, haarWavelet μ A B x ∂μ = 0 := by
    exact integral_haarWavelet_eq_zero_of_pos
      μ A B hAB hA_meas hB_meas hA_pos hB_pos
  let cD : ℝ := 1 / (μ D).toReal
  have hCD' := Set.disjoint_left.mp hCD
  let _ := hAB
  let _ := hC_meas
  have hmul_eq :
      (fun x => haarWavelet μ A B x * haarWavelet μ C D x)
        = fun x => (-cD) * haarWavelet μ A B x := by
    funext x
    by_cases hxU : x ∈ A ∪ B
    · have hxD : x ∈ D := hsub hxU
      have hxC : x ∉ C := by
        intro hxC
        exact (hCD' hxC hxD).elim
      simp [haarWavelet, cD, hxD, hxC, mul_comm]
    · have hxA : x ∉ A := by
        intro hxA
        exact hxU (Or.inl hxA)
      have hxB : x ∉ B := by
        intro hxB
        exact hxU (Or.inr hxB)
      simp [haarWavelet, hxA, hxB]
  rw [hmul_eq, MeasureTheory.integral_const_mul, hmean_zero]
  simp

structure HaarSystem (G : GoodGrid (α := α)) [DecidableEq (Set α)] where
  binaryRefinement : BinaryRefinementOfGoodGrid G
  haarWavelets : ∀ n (Q : Set α) (hQ : Q ∈ G.grid.partitions n),
      {p : Finset (Set α) × Finset (Set α) //
        p ∈ (binaryRefinement.tree n Q hQ).Branches} → α → ℝ
  haarWavelets_def :
      ∀ n Q hQ
        (p : {p : Finset (Set α) × Finset (Set α) //
          p ∈ (binaryRefinement.tree n Q hQ).Branches}),
        haarWavelets n Q hQ p = haarWavelet G.μ (branchSupport p.1.1) (branchSupport p.1.2)

/-- The normalized father function `1_α / μ(α)`, written as indicator on `Set.univ`. -/
noncomputable def normalizedAlphaFunction
    (G : GoodGrid (α := α)) : α → ℝ :=
  fun x =>
    Set.indicator (Set.univ : Set α)
      (fun _ => 1 / (G.μ Set.univ).toReal) x

/-- A full Haar system: a Haar system plus the normalized father function `1_α / μ(α)`. -/
structure FullHaarSystem (G : GoodGrid (α := α)) [DecidableEq (Set α)] extends HaarSystem G where
  alphaFunction : α → ℝ
  alphaFunction_def : alphaFunction = normalizedAlphaFunction G

/-- Orthogonality in `L²(μ)` for two distinct Haar wavelets in the same Haar system,
assuming the usual support relation (disjointness or inclusion) and positivity/measurability
for the first wavelet. -/
theorem HaarSystem.integral_mul_haarWavelets_eq_zero_of_distinct_core
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (n : ℕ) (Q : Set α) (hQ : Q ∈ G.grid.partitions n)
    (p q : {r : Finset (Set α) × Finset (Set α) //
      r ∈ (H.binaryRefinement.tree n Q hQ).Branches})
    (hpq : p ≠ q)
    (hAB : Disjoint (branchSupport p.1.1) (branchSupport p.1.2))
    (hCD : Disjoint (branchSupport q.1.1) (branchSupport q.1.2))
    (hC_meas : MeasurableSet (branchSupport q.1.1))
    (hA_meas : MeasurableSet (branchSupport p.1.1))
    (hB_meas : MeasurableSet (branchSupport p.1.2))
    (hA_pos : 0 < G.μ (branchSupport p.1.1))
    (hB_pos : 0 < G.μ (branchSupport p.1.2))
    (hrel :
      Disjoint
        (branchSupport p.1.1 ∪ branchSupport p.1.2)
        (branchSupport q.1.1 ∪ branchSupport q.1.2)
      ∨ branchSupport p.1.1 ∪ branchSupport p.1.2 ⊆ branchSupport q.1.1
      ∨ branchSupport p.1.1 ∪ branchSupport p.1.2 ⊆ branchSupport q.1.2) :
    ∫ x, H.haarWavelets n Q hQ p x * H.haarWavelets n Q hQ q x ∂ G.μ = 0 := by
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  let _ := hpq
  rw [H.haarWavelets_def, H.haarWavelets_def]
  rcases hrel with hdisj | hsub_left | hsub_right
  · have hAC : Disjoint (branchSupport p.1.1) (branchSupport q.1.1) :=
      (hdisj.mono_left Set.subset_union_left).mono_right Set.subset_union_left
    have hAD : Disjoint (branchSupport p.1.1) (branchSupport q.1.2) :=
      (hdisj.mono_left Set.subset_union_left).mono_right Set.subset_union_right
    have hBC : Disjoint (branchSupport p.1.2) (branchSupport q.1.1) :=
      (hdisj.mono_left Set.subset_union_right).mono_right Set.subset_union_left
    have hBD : Disjoint (branchSupport p.1.2) (branchSupport q.1.2) :=
      (hdisj.mono_left Set.subset_union_right).mono_right Set.subset_union_right
    exact integral_mul_haarWavelet_eq_zero_of_disjoint
      G.μ (branchSupport p.1.1) (branchSupport p.1.2)
      (branchSupport q.1.1) (branchSupport q.1.2)
      hAC hAD hBC hBD
  · exact integral_mul_haarWavelet_eq_zero_of_subset_left
      G.μ
      (branchSupport p.1.1) (branchSupport p.1.2)
      (branchSupport q.1.1) (branchSupport q.1.2)
      hAB hCD hsub_left hA_meas hB_meas hA_pos hB_pos
  · exact integral_mul_haarWavelet_eq_zero_of_subset_right
      G.μ
      (branchSupport p.1.1) (branchSupport p.1.2)
      (branchSupport q.1.1) (branchSupport q.1.2)
      hAB hCD hsub_right hC_meas
      hA_meas hB_meas hA_pos hB_pos

/-- Orthogonality in `L²(μ)` for two distinct Haar wavelets in the same Haar system,
with the support relation automatically derived from the tree `SupportProperty`. -/
theorem HaarSystem.integral_mul_haarWavelets_eq_zero_of_distinct
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (n : ℕ) (Q : Set α) (hQ : Q ∈ G.grid.partitions n)
    (p q : {r : Finset (Set α) × Finset (Set α) //
      r ∈ (H.binaryRefinement.tree n Q hQ).Branches})
    (hpq : p ≠ q) :
    ∫ x, H.haarWavelets n Q hQ p x * H.haarWavelets n Q hQ q x ∂ G.μ = 0 := by
  let T := H.binaryRefinement.tree n Q hQ
  have hpq_val : p.1 ≠ q.1 := by
    intro h
    exact hpq (Subtype.ext h)
  have hp_childs : p.1.1 ⊆ T.Childs ∧ p.1.2 ⊆ T.Childs :=
    T.TreeStructureChilds p.1 p.2
  have hq_childs : q.1.1 ⊆ T.Childs ∧ q.1.2 ⊆ T.Childs :=
    T.TreeStructureChilds q.1 q.2
  have hp1_part : ∀ s, s ∈ p.1.1 → s ∈ G.grid.partitions (n + 1) := by
    intro s hs
    have hs_child : s ∈ T.Childs := hp_childs.1 hs
    exact (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child |>.1
  have hp2_part : ∀ s, s ∈ p.1.2 → s ∈ G.grid.partitions (n + 1) := by
    intro s hs
    have hs_child : s ∈ T.Childs := hp_childs.2 hs
    exact (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child |>.1
  have hq1_part : ∀ s, s ∈ q.1.1 → s ∈ G.grid.partitions (n + 1) := by
    intro s hs
    have hs_child : s ∈ T.Childs := hq_childs.1 hs
    exact (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child |>.1
  have hq2_part : ∀ s, s ∈ q.1.2 → s ∈ G.grid.partitions (n + 1) := by
    intro s hs
    have hs_child : s ∈ T.Childs := hq_childs.2 hs
    exact (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child |>.1
  have hp_nonempty : p.1.1.Nonempty ∧ p.1.2.Nonempty := T.NonemptyPairs p.1 p.2
  have hq_nonempty : q.1.1.Nonempty ∧ q.1.2.Nonempty := T.NonemptyPairs q.1 q.2
  have hAB_cells : Disjoint p.1.1 p.1.2 := T.DisjointComponents p.1 p.2
  have hCD_cells : Disjoint q.1.1 q.1.2 := T.DisjointComponents q.1 q.2
  have hp1_pos_cells : ∀ s, s ∈ p.1.1 → 0 < G.μ s := by
    intro s hs
    exact G.positive_measure (n + 1) s (hp1_part s hs)
  have hp2_pos_cells : ∀ s, s ∈ p.1.2 → 0 < G.μ s := by
    intro s hs
    exact G.positive_measure (n + 1) s (hp2_part s hs)
  have hq1_pos_cells : ∀ s, s ∈ q.1.1 → 0 < G.μ s := by
    intro s hs
    exact G.positive_measure (n + 1) s (hq1_part s hs)
  have hq2_pos_cells : ∀ s, s ∈ q.1.2 → 0 < G.μ s := by
    intro s hs
    exact G.positive_measure (n + 1) s (hq2_part s hs)
  have hAB : Disjoint (branchSupport p.1.1) (branchSupport p.1.2) :=
    disjoint_branchSupport_of_finset_disjoint G n p.1.1 p.1.2 hp1_part hp2_part hAB_cells
  have hCD : Disjoint (branchSupport q.1.1) (branchSupport q.1.2) :=
    disjoint_branchSupport_of_finset_disjoint G n q.1.1 q.1.2 hq1_part hq2_part hCD_cells
  have hA_meas : MeasurableSet (branchSupport p.1.1) :=
    measurableSet_branchSupport_of_partition G n p.1.1 hp1_part
  have hB_meas : MeasurableSet (branchSupport p.1.2) :=
    measurableSet_branchSupport_of_partition G n p.1.2 hp2_part
  have hC_meas : MeasurableSet (branchSupport q.1.1) :=
    measurableSet_branchSupport_of_partition G n q.1.1 hq1_part
  have hD_meas : MeasurableSet (branchSupport q.1.2) :=
    measurableSet_branchSupport_of_partition G n q.1.2 hq2_part
  have hA_pos : 0 < G.μ (branchSupport p.1.1) :=
    measure_branchSupport_pos_of_nonempty G p.1.1 hp1_pos_cells hp_nonempty.1
  have hB_pos : 0 < G.μ (branchSupport p.1.2) :=
    measure_branchSupport_pos_of_nonempty G p.1.2 hp2_pos_cells hp_nonempty.2
  have hC_pos : 0 < G.μ (branchSupport q.1.1) :=
    measure_branchSupport_pos_of_nonempty G q.1.1 hq1_pos_cells hq_nonempty.1
  have hD_pos : 0 < G.μ (branchSupport q.1.2) :=
    measure_branchSupport_pos_of_nonempty G q.1.2 hq2_pos_cells hq_nonempty.2

  have hsupport := T.SupportProperty p.1 p.2 q.1 q.2 hpq_val
  rcases hsupport with hdisjCells | hpSubq1 | hpSubq2 | hqSubp1 | hqSubp2
  · have hAC_cells : Disjoint p.1.1 q.1.1 := by
      refine Finset.disjoint_left.2 ?_
      intro s hsA hsC
      exact (Finset.disjoint_left.mp hdisjCells)
        (Finset.mem_union.mpr (Or.inl hsA))
        (Finset.mem_union.mpr (Or.inl hsC))
    have hAD_cells : Disjoint p.1.1 q.1.2 := by
      refine Finset.disjoint_left.2 ?_
      intro s hsA hsD
      exact (Finset.disjoint_left.mp hdisjCells)
        (Finset.mem_union.mpr (Or.inl hsA))
        (Finset.mem_union.mpr (Or.inr hsD))
    have hBC_cells : Disjoint p.1.2 q.1.1 := by
      refine Finset.disjoint_left.2 ?_
      intro s hsB hsC
      exact (Finset.disjoint_left.mp hdisjCells)
        (Finset.mem_union.mpr (Or.inr hsB))
        (Finset.mem_union.mpr (Or.inl hsC))
    have hBD_cells : Disjoint p.1.2 q.1.2 := by
      refine Finset.disjoint_left.2 ?_
      intro s hsB hsD
      exact (Finset.disjoint_left.mp hdisjCells)
        (Finset.mem_union.mpr (Or.inr hsB))
        (Finset.mem_union.mpr (Or.inr hsD))
    have hAC : Disjoint (branchSupport p.1.1) (branchSupport q.1.1) :=
      disjoint_branchSupport_of_finset_disjoint G n p.1.1 q.1.1 hp1_part hq1_part hAC_cells
    have hAD : Disjoint (branchSupport p.1.1) (branchSupport q.1.2) :=
      disjoint_branchSupport_of_finset_disjoint G n p.1.1 q.1.2 hp1_part hq2_part hAD_cells
    have hBC : Disjoint (branchSupport p.1.2) (branchSupport q.1.1) :=
      disjoint_branchSupport_of_finset_disjoint G n p.1.2 q.1.1 hp2_part hq1_part hBC_cells
    have hBD : Disjoint (branchSupport p.1.2) (branchSupport q.1.2) :=
      disjoint_branchSupport_of_finset_disjoint G n p.1.2 q.1.2 hp2_part hq2_part hBD_cells
    rw [H.haarWavelets_def, H.haarWavelets_def]
    exact integral_mul_haarWavelet_eq_zero_of_disjoint
      G.μ (branchSupport p.1.1) (branchSupport p.1.2)
      (branchSupport q.1.1) (branchSupport q.1.2)
      hAC hAD hBC hBD
  · have hp1_sub_q1 : p.1.1 ⊆ q.1.1 := by
      intro s hs
      exact hpSubq1 (Finset.mem_union.mpr (Or.inl hs))
    have hp2_sub_q1 : p.1.2 ⊆ q.1.1 := by
      intro s hs
      exact hpSubq1 (Finset.mem_union.mpr (Or.inr hs))
    have hsub : branchSupport p.1.1 ∪ branchSupport p.1.2 ⊆ branchSupport q.1.1 :=
      Set.union_subset (branchSupport_mono hp1_sub_q1) (branchSupport_mono hp2_sub_q1)
    exact HaarSystem.integral_mul_haarWavelets_eq_zero_of_distinct_core
      G H n Q hQ p q hpq hAB hCD hC_meas hA_meas hB_meas hA_pos hB_pos
      (Or.inr (Or.inl hsub))
  · have hp1_sub_q2 : p.1.1 ⊆ q.1.2 := by
      intro s hs
      exact hpSubq2 (Finset.mem_union.mpr (Or.inl hs))
    have hp2_sub_q2 : p.1.2 ⊆ q.1.2 := by
      intro s hs
      exact hpSubq2 (Finset.mem_union.mpr (Or.inr hs))
    have hsub : branchSupport p.1.1 ∪ branchSupport p.1.2 ⊆ branchSupport q.1.2 :=
      Set.union_subset (branchSupport_mono hp1_sub_q2) (branchSupport_mono hp2_sub_q2)
    exact HaarSystem.integral_mul_haarWavelets_eq_zero_of_distinct_core
      G H n Q hQ p q hpq hAB hCD hC_meas hA_meas hB_meas hA_pos hB_pos
      (Or.inr (Or.inr hsub))
  · have hq1_sub_p1 : q.1.1 ⊆ p.1.1 := by
      intro s hs
      exact hqSubp1 (Finset.mem_union.mpr (Or.inl hs))
    have hq2_sub_p1 : q.1.2 ⊆ p.1.1 := by
      intro s hs
      exact hqSubp1 (Finset.mem_union.mpr (Or.inr hs))
    have hsub_swap : branchSupport q.1.1 ∪ branchSupport q.1.2 ⊆ branchSupport p.1.1 :=
      Set.union_subset (branchSupport_mono hq1_sub_p1) (branchSupport_mono hq2_sub_p1)
    have hswap :
        ∫ x, H.haarWavelets n Q hQ q x * H.haarWavelets n Q hQ p x ∂ G.μ = 0 :=
      HaarSystem.integral_mul_haarWavelets_eq_zero_of_distinct_core
        G H n Q hQ q p (by simpa [ne_eq] using hpq.symm)
        hCD hAB hA_meas hC_meas hD_meas hC_pos hD_pos
        (Or.inr (Or.inl hsub_swap))
    have hmul_comm :
        (fun x => H.haarWavelets n Q hQ p x * H.haarWavelets n Q hQ q x)
          = (fun x => H.haarWavelets n Q hQ q x * H.haarWavelets n Q hQ p x) := by
      funext x
      rw [mul_comm]
    rw [hmul_comm]
    exact hswap
  · have hq1_sub_p2 : q.1.1 ⊆ p.1.2 := by
      intro s hs
      exact hqSubp2 (Finset.mem_union.mpr (Or.inl hs))
    have hq2_sub_p2 : q.1.2 ⊆ p.1.2 := by
      intro s hs
      exact hqSubp2 (Finset.mem_union.mpr (Or.inr hs))
    have hsub_swap : branchSupport q.1.1 ∪ branchSupport q.1.2 ⊆ branchSupport p.1.2 :=
      Set.union_subset (branchSupport_mono hq1_sub_p2) (branchSupport_mono hq2_sub_p2)
    have hswap :
        ∫ x, H.haarWavelets n Q hQ q x * H.haarWavelets n Q hQ p x ∂ G.μ = 0 :=
      HaarSystem.integral_mul_haarWavelets_eq_zero_of_distinct_core
        G H n Q hQ q p (by simpa [ne_eq] using hpq.symm)
        hCD hAB hA_meas hC_meas hD_meas hC_pos hD_pos
        (Or.inr (Or.inr hsub_swap))
    have hmul_comm :
        (fun x => H.haarWavelets n Q hQ p x * H.haarWavelets n Q hQ q x)
          = (fun x => H.haarWavelets n Q hQ q x * H.haarWavelets n Q hQ p x) := by
      funext x
      rw [mul_comm]
    rw [hmul_comm]
    exact hswap

theorem HaarSystem.integral_mul_haarWavelets_eq_zero_of_distinct_distinct_Q
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (n : ℕ)
    (Q : Set α)
    (hQ : Q ∈ G.grid.partitions n)
    (P : Set α)
    (hP : P ∈ G.grid.partitions n)
    (q : {r : Finset (Set α) × Finset (Set α) //
      r ∈ (H.binaryRefinement.tree n Q hQ).Branches})
    (p : {r : Finset (Set α) × Finset (Set α) //
      r ∈ (H.binaryRefinement.tree n P hP).Branches})
    (hPQ : P ≠ Q) :
    ∫ x, H.haarWavelets n Q hQ q x * H.haarWavelets n P hP p x ∂ G.μ = 0 := by
  let TP := H.binaryRefinement.tree n P hP
  let TQ := H.binaryRefinement.tree n Q hQ
  have hQP_disj : Disjoint Q P := (G.grid.disjoint n P Q hP hQ hPQ).symm
  have hp_childs : p.1.1 ⊆ TP.Childs ∧ p.1.2 ⊆ TP.Childs :=
    TP.TreeStructureChilds p.1 p.2
  have hq_childs : q.1.1 ⊆ TQ.Childs ∧ q.1.2 ⊆ TQ.Childs :=
    TQ.TreeStructureChilds q.1 q.2
  have hp1_sub_P : branchSupport p.1.1 ⊆ P := by
    intro x hx
    rcases (by simpa [branchSupport] using hx) with ⟨s, hs, hxs⟩
    have hs_child : s ∈ TP.Childs := hp_childs.1 hs
    have hs_children : s ∈ G.children n P :=
      (H.binaryRefinement.childs_are_children n P hP s).1 hs_child
    exact hs_children.2 hxs
  have hp2_sub_P : branchSupport p.1.2 ⊆ P := by
    intro x hx
    rcases (by simpa [branchSupport] using hx) with ⟨s, hs, hxs⟩
    have hs_child : s ∈ TP.Childs := hp_childs.2 hs
    have hs_children : s ∈ G.children n P :=
      (H.binaryRefinement.childs_are_children n P hP s).1 hs_child
    exact hs_children.2 hxs
  have hq1_sub_Q : branchSupport q.1.1 ⊆ Q := by
    intro x hx
    rcases (by simpa [branchSupport] using hx) with ⟨s, hs, hxs⟩
    have hs_child : s ∈ TQ.Childs := hq_childs.1 hs
    have hs_children : s ∈ G.children n Q :=
      (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child
    exact hs_children.2 hxs
  have hq2_sub_Q : branchSupport q.1.2 ⊆ Q := by
    intro x hx
    rcases (by simpa [branchSupport] using hx) with ⟨s, hs, hxs⟩
    have hs_child : s ∈ TQ.Childs := hq_childs.2 hs
    have hs_children : s ∈ G.children n Q :=
      (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child
    exact hs_children.2 hxs
  have hAC : Disjoint (branchSupport q.1.1) (branchSupport p.1.1) :=
    (hQP_disj.mono_left hq1_sub_Q).mono_right hp1_sub_P
  have hAD : Disjoint (branchSupport q.1.1) (branchSupport p.1.2) :=
    (hQP_disj.mono_left hq1_sub_Q).mono_right hp2_sub_P
  have hBC : Disjoint (branchSupport q.1.2) (branchSupport p.1.1) :=
    (hQP_disj.mono_left hq2_sub_Q).mono_right hp1_sub_P
  have hBD : Disjoint (branchSupport q.1.2) (branchSupport p.1.2) :=
    (hQP_disj.mono_left hq2_sub_Q).mono_right hp2_sub_P
  rw [H.haarWavelets_def, H.haarWavelets_def]
  exact integral_mul_haarWavelet_eq_zero_of_disjoint
    G.μ (branchSupport q.1.1) (branchSupport q.1.2)
    (branchSupport p.1.1) (branchSupport p.1.2)
    hAC hAD hBC hBD

structure HaarSystem.Index
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) where
  level : ℕ
  cell : Set α
  hcell : cell ∈ G.grid.partitions level
  branch : {r : Finset (Set α) × Finset (Set α) //
    r ∈ (H.binaryRefinement.tree level cell hcell).Branches}

def HaarSystem.wavelet
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (i : H.Index) : α → ℝ :=
  H.haarWavelets i.level i.cell i.hcell i.branch

theorem HaarSystem.integral_mul_haarWavelets_eq_zero_of_lt_level
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (n m : ℕ)
    (hnm : n < m)
    (Q : Set α)
    (hQ : Q ∈ G.grid.partitions n)
    (q : {r : Finset (Set α) × Finset (Set α) //
      r ∈ (H.binaryRefinement.tree n Q hQ).Branches})
    (P : Set α)
    (hP : P ∈ G.grid.partitions m)
    (p : {r : Finset (Set α) × Finset (Set α) //
      r ∈ (H.binaryRefinement.tree m P hP).Branches}) :
    ∫ x, H.haarWavelets m P hP p x * H.haarWavelets n Q hQ q x ∂ G.μ = 0 := by
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  let TP := H.binaryRefinement.tree m P hP
  let TQ := H.binaryRefinement.tree n Q hQ
  have hp_childs : p.1.1 ⊆ TP.Childs ∧ p.1.2 ⊆ TP.Childs :=
    TP.TreeStructureChilds p.1 p.2
  have hq_childs : q.1.1 ⊆ TQ.Childs ∧ q.1.2 ⊆ TQ.Childs :=
    TQ.TreeStructureChilds q.1 q.2
  have hp1_part : ∀ s, s ∈ p.1.1 → s ∈ G.grid.partitions (m + 1) := by
    intro s hs
    have hs_child : s ∈ TP.Childs := hp_childs.1 hs
    exact (H.binaryRefinement.childs_are_children m P hP s).1 hs_child |>.1
  have hp2_part : ∀ s, s ∈ p.1.2 → s ∈ G.grid.partitions (m + 1) := by
    intro s hs
    have hs_child : s ∈ TP.Childs := hp_childs.2 hs
    exact (H.binaryRefinement.childs_are_children m P hP s).1 hs_child |>.1
  have hq1_part : ∀ s, s ∈ q.1.1 → s ∈ G.grid.partitions (n + 1) := by
    intro s hs
    have hs_child : s ∈ TQ.Childs := hq_childs.1 hs
    exact (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child |>.1
  have hq2_part : ∀ s, s ∈ q.1.2 → s ∈ G.grid.partitions (n + 1) := by
    intro s hs
    have hs_child : s ∈ TQ.Childs := hq_childs.2 hs
    exact (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child |>.1
  have hp_nonempty : p.1.1.Nonempty ∧ p.1.2.Nonempty := TP.NonemptyPairs p.1 p.2
  have hAB_cells : Disjoint p.1.1 p.1.2 := TP.DisjointComponents p.1 p.2
  have hCD_cells : Disjoint q.1.1 q.1.2 := TQ.DisjointComponents q.1 q.2
  have hp1_pos_cells : ∀ s, s ∈ p.1.1 → 0 < G.μ s := by
    intro s hs
    exact G.positive_measure (m + 1) s (hp1_part s hs)
  have hp2_pos_cells : ∀ s, s ∈ p.1.2 → 0 < G.μ s := by
    intro s hs
    exact G.positive_measure (m + 1) s (hp2_part s hs)
  have hAB : Disjoint (branchSupport p.1.1) (branchSupport p.1.2) :=
    disjoint_branchSupport_of_finset_disjoint G m p.1.1 p.1.2 hp1_part hp2_part hAB_cells
  have hCD : Disjoint (branchSupport q.1.1) (branchSupport q.1.2) :=
    disjoint_branchSupport_of_finset_disjoint G n q.1.1 q.1.2 hq1_part hq2_part hCD_cells
  have hA_meas : MeasurableSet (branchSupport p.1.1) :=
    measurableSet_branchSupport_of_partition G m p.1.1 hp1_part
  have hB_meas : MeasurableSet (branchSupport p.1.2) :=
    measurableSet_branchSupport_of_partition G m p.1.2 hp2_part
  have hA_pos : 0 < G.μ (branchSupport p.1.1) :=
    measure_branchSupport_pos_of_nonempty G p.1.1 hp1_pos_cells hp_nonempty.1
  have hB_pos : 0 < G.μ (branchSupport p.1.2) :=
    measure_branchSupport_pos_of_nonempty G p.1.2 hp2_pos_cells hp_nonempty.2
  have hp1_sub_P : branchSupport p.1.1 ⊆ P := by
    intro x hx
    rcases (by simpa [branchSupport] using hx) with ⟨s, hs, hxs⟩
    have hs_child : s ∈ TP.Childs := hp_childs.1 hs
    have hs_children : s ∈ G.children m P :=
      (H.binaryRefinement.childs_are_children m P hP s).1 hs_child
    exact hs_children.2 hxs
  have hp2_sub_P : branchSupport p.1.2 ⊆ P := by
    intro x hx
    rcases (by simpa [branchSupport] using hx) with ⟨s, hs, hxs⟩
    have hs_child : s ∈ TP.Childs := hp_childs.2 hs
    have hs_children : s ∈ G.children m P :=
      (H.binaryRefinement.childs_are_children m P hP s).1 hs_child
    exact hs_children.2 hxs
  have hq1_sub_Q : branchSupport q.1.1 ⊆ Q := by
    intro x hx
    rcases (by simpa [branchSupport] using hx) with ⟨s, hs, hxs⟩
    have hs_child : s ∈ TQ.Childs := hq_childs.1 hs
    have hs_children : s ∈ G.children n Q :=
      (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child
    exact hs_children.2 hxs
  have hq2_sub_Q : branchSupport q.1.2 ⊆ Q := by
    intro x hx
    rcases (by simpa [branchSupport] using hx) with ⟨s, hs, hxs⟩
    have hs_child : s ∈ TQ.Childs := hq_childs.2 hs
    have hs_children : s ∈ G.children n Q :=
      (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child
    exact hs_children.2 hxs
  have hPQ_cases : P ⊆ Q ∨ Disjoint P Q :=
    G.partition_subset_or_disjoint_of_le n m hnm.le Q hQ P hP
  rcases hPQ_cases with hPQ_sub | hPQ_disj
  · obtain ⟨c, hc_child, hPc⟩ := G.exists_child_containing_of_lt n m hnm Q hQ P hP hPQ_sub
    have hc_in_childs : c ∈ TQ.Childs :=
      (H.binaryRefinement.childs_are_children n Q hQ c).2 hc_child
    have hp1_sub_c : branchSupport p.1.1 ⊆ c := hp1_sub_P.trans hPc
    have hp2_sub_c : branchSupport p.1.2 ⊆ c := hp2_sub_P.trans hPc
    by_cases hc_q1 : c ∈ q.1.1
    · have hsub : branchSupport p.1.1 ∪ branchSupport p.1.2 ⊆ branchSupport q.1.1 := by
        refine Set.union_subset ?_ ?_
        · exact hp1_sub_c.trans (subset_branchSupport_of_mem hc_q1)
        · exact hp2_sub_c.trans (subset_branchSupport_of_mem hc_q1)
      rw [H.haarWavelets_def, H.haarWavelets_def]
      exact integral_mul_haarWavelet_eq_zero_of_subset_left
        G.μ
        (branchSupport p.1.1) (branchSupport p.1.2)
        (branchSupport q.1.1) (branchSupport q.1.2)
        hAB hCD hsub hA_meas hB_meas hA_pos hB_pos
    · by_cases hc_q2 : c ∈ q.1.2
      · have hsub : branchSupport p.1.1 ∪ branchSupport p.1.2 ⊆ branchSupport q.1.2 := by
          refine Set.union_subset ?_ ?_
          · exact hp1_sub_c.trans (subset_branchSupport_of_mem hc_q2)
          · exact hp2_sub_c.trans (subset_branchSupport_of_mem hc_q2)
        rw [H.haarWavelets_def, H.haarWavelets_def]
        exact integral_mul_haarWavelet_eq_zero_of_subset_right
          G.μ
          (branchSupport p.1.1) (branchSupport p.1.2)
          (branchSupport q.1.1) (branchSupport q.1.2)
          hAB hCD hsub
          (measurableSet_branchSupport_of_partition G n q.1.1 hq1_part)
          hA_meas hB_meas hA_pos hB_pos
      · have hc_not_support : c ∉ q.1.1 ∪ q.1.2 := by
          simp [hc_q1, hc_q2]
        have hc_q1_disj : Disjoint c (branchSupport q.1.1) := by
          refine Set.disjoint_left.2 ?_
          intro x hxc hxq
          rcases (by simpa [branchSupport] using hxq) with ⟨s, hs, hxs⟩
          have hs_ne : s ≠ c := by
            intro hsc
            exact hc_q1 (hsc ▸ hs)
          have hs_disj : Disjoint s c :=
            G.grid.disjoint (n + 1) s c (hq1_part s hs) hc_child.1 hs_ne
          exact (Set.disjoint_left.mp hs_disj hxs hxc).elim
        have hc_q2_disj : Disjoint c (branchSupport q.1.2) := by
          refine Set.disjoint_left.2 ?_
          intro x hxc hxq
          rcases (by simpa [branchSupport] using hxq) with ⟨s, hs, hxs⟩
          have hs_ne : s ≠ c := by
            intro hsc
            exact hc_q2 (hsc ▸ hs)
          have hs_disj : Disjoint s c :=
            G.grid.disjoint (n + 1) s c (hq2_part s hs) hc_child.1 hs_ne
          exact (Set.disjoint_left.mp hs_disj hxs hxc).elim
        have hAC : Disjoint (branchSupport p.1.1) (branchSupport q.1.1) :=
          hc_q1_disj.mono_left hp1_sub_c
        have hAD : Disjoint (branchSupport p.1.1) (branchSupport q.1.2) :=
          hc_q2_disj.mono_left hp1_sub_c
        have hBC : Disjoint (branchSupport p.1.2) (branchSupport q.1.1) :=
          hc_q1_disj.mono_left hp2_sub_c
        have hBD : Disjoint (branchSupport p.1.2) (branchSupport q.1.2) :=
          hc_q2_disj.mono_left hp2_sub_c
        rw [H.haarWavelets_def, H.haarWavelets_def]
        exact integral_mul_haarWavelet_eq_zero_of_disjoint
          G.μ (branchSupport p.1.1) (branchSupport p.1.2)
          (branchSupport q.1.1) (branchSupport q.1.2)
          hAC hAD hBC hBD
  · have hAC : Disjoint (branchSupport p.1.1) (branchSupport q.1.1) :=
      (hPQ_disj.mono_left hp1_sub_P).mono_right hq1_sub_Q
    have hAD : Disjoint (branchSupport p.1.1) (branchSupport q.1.2) :=
      (hPQ_disj.mono_left hp1_sub_P).mono_right hq2_sub_Q
    have hBC : Disjoint (branchSupport p.1.2) (branchSupport q.1.1) :=
      (hPQ_disj.mono_left hp2_sub_P).mono_right hq1_sub_Q
    have hBD : Disjoint (branchSupport p.1.2) (branchSupport q.1.2) :=
      (hPQ_disj.mono_left hp2_sub_P).mono_right hq2_sub_Q
    rw [H.haarWavelets_def, H.haarWavelets_def]
    exact integral_mul_haarWavelet_eq_zero_of_disjoint
      G.μ (branchSupport p.1.1) (branchSupport p.1.2)
      (branchSupport q.1.1) (branchSupport q.1.2)
      hAC hAD hBC hBD

theorem HaarSystem.integral_mul_wavelet_eq_zero_of_ne
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (i j : H.Index)
    (hij : i ≠ j) :
  ∫ x, HaarSystem.wavelet G H i x * HaarSystem.wavelet G H j x ∂ G.μ = 0 := by
  rcases i with ⟨ni, Qi, hQi, pi⟩
  rcases j with ⟨nj, Qj, hQj, pj⟩
  dsimp [HaarSystem.wavelet]
  rcases lt_trichotomy ni nj with hlt | hEq | hgt
  · have hswap :
        ∫ x, H.haarWavelets nj Qj hQj pj x * H.haarWavelets ni Qi hQi pi x ∂ G.μ = 0 :=
      HaarSystem.integral_mul_haarWavelets_eq_zero_of_lt_level
        G H ni nj hlt Qi hQi pi Qj hQj pj
    have hmul_comm :
        (fun x => H.haarWavelets ni Qi hQi pi x * H.haarWavelets nj Qj hQj pj x)
          = (fun x => H.haarWavelets nj Qj hQj pj x * H.haarWavelets ni Qi hQi pi x) := by
      funext x
      rw [mul_comm]
    rw [hmul_comm]
    exact hswap
  · subst hEq
    by_cases hQQ : Qi = Qj
    · subst hQQ
      have hproof : hQi = hQj := Subsingleton.elim _ _
      subst hQj
      have hpij : pi ≠ pj := by
        intro hpij
        apply hij
        cases hpij
        rfl
      exact HaarSystem.integral_mul_haarWavelets_eq_zero_of_distinct
        G H ni Qi hQi pi pj hpij
    · exact HaarSystem.integral_mul_haarWavelets_eq_zero_of_distinct_distinct_Q
        G H ni Qi hQi Qj hQj pi pj (by
          intro h
          apply hQQ
          exact h.symm)
  · exact HaarSystem.integral_mul_haarWavelets_eq_zero_of_lt_level
      G H nj ni hgt Qj hQj pj Qi hQi pi

theorem HaarSystem.integral_wavelet_eq_zero
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (i : H.Index) :
    ∫ x, HaarSystem.wavelet G H i x ∂ G.μ = 0 := by
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  rcases i with ⟨n, Q, hQ, p⟩
  dsimp [HaarSystem.wavelet]
  let T := H.binaryRefinement.tree n Q hQ
  have hp_childs : p.1.1 ⊆ T.Childs ∧ p.1.2 ⊆ T.Childs :=
    T.TreeStructureChilds p.1 p.2
  have hp1_part : ∀ s, s ∈ p.1.1 → s ∈ G.grid.partitions (n + 1) := by
    intro s hs
    have hs_child : s ∈ T.Childs := hp_childs.1 hs
    exact (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child |>.1
  have hp2_part : ∀ s, s ∈ p.1.2 → s ∈ G.grid.partitions (n + 1) := by
    intro s hs
    have hs_child : s ∈ T.Childs := hp_childs.2 hs
    exact (H.binaryRefinement.childs_are_children n Q hQ s).1 hs_child |>.1
  have hp_nonempty : p.1.1.Nonempty ∧ p.1.2.Nonempty := T.NonemptyPairs p.1 p.2
  have hAB_cells : Disjoint p.1.1 p.1.2 := T.DisjointComponents p.1 p.2
  have hp1_pos_cells : ∀ s, s ∈ p.1.1 → 0 < G.μ s := by
    intro s hs
    exact G.positive_measure (n + 1) s (hp1_part s hs)
  have hp2_pos_cells : ∀ s, s ∈ p.1.2 → 0 < G.μ s := by
    intro s hs
    exact G.positive_measure (n + 1) s (hp2_part s hs)
  have hAB : Disjoint (branchSupport p.1.1) (branchSupport p.1.2) :=
    disjoint_branchSupport_of_finset_disjoint G n p.1.1 p.1.2 hp1_part hp2_part hAB_cells
  have hA_meas : MeasurableSet (branchSupport p.1.1) :=
    measurableSet_branchSupport_of_partition G n p.1.1 hp1_part
  have hB_meas : MeasurableSet (branchSupport p.1.2) :=
    measurableSet_branchSupport_of_partition G n p.1.2 hp2_part
  have hA_pos : 0 < G.μ (branchSupport p.1.1) :=
    measure_branchSupport_pos_of_nonempty G p.1.1 hp1_pos_cells hp_nonempty.1
  have hB_pos : 0 < G.μ (branchSupport p.1.2) :=
    measure_branchSupport_pos_of_nonempty G p.1.2 hp2_pos_cells hp_nonempty.2
  rw [H.haarWavelets_def]
  exact integral_haarWavelet_eq_zero_of_pos
    G.μ (branchSupport p.1.1) (branchSupport p.1.2)
    hAB hA_meas hB_meas hA_pos hB_pos

inductive FullHaarSystem.Index
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (F : FullHaarSystem (G := G)) where
  | alpha
  | wavelet (i : F.toHaarSystem.Index)

def FullHaarSystem.function
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (F : FullHaarSystem (G := G))
    (i : F.Index) : α → ℝ :=
  match i with
  | .alpha => F.alphaFunction
  | .wavelet j => HaarSystem.wavelet G F.toHaarSystem j

theorem FullHaarSystem.integral_mul_function_eq_zero_of_ne
    (G : GoodGrid (α := α)) [DecidableEq (Set α)]
    (F : FullHaarSystem (G := G))
    (i j : F.Index)
    (hij : i ≠ j) :
    ∫ x, FullHaarSystem.function G F i x * FullHaarSystem.function G F j x ∂ G.μ = 0 := by
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  cases i with
  | alpha =>
      cases j with
      | alpha =>
          exact (hij rfl).elim
      | wavelet jw =>
          rw [FullHaarSystem.function, FullHaarSystem.function, F.alphaFunction_def]
          let c : ℝ := 1 / (G.μ Set.univ).toReal
          have hmul_eq :
              (fun x => normalizedAlphaFunction G x * HaarSystem.wavelet G F.toHaarSystem jw x)
                = (fun x => c * HaarSystem.wavelet G F.toHaarSystem jw x) := by
            funext x
            simp [normalizedAlphaFunction, c]
          rw [hmul_eq, MeasureTheory.integral_const_mul]
          rw [HaarSystem.integral_wavelet_eq_zero G F.toHaarSystem jw]
          simp
  | wavelet iw =>
      cases j with
      | alpha =>
          rw [FullHaarSystem.function, FullHaarSystem.function, F.alphaFunction_def]
          let c : ℝ := 1 / (G.μ Set.univ).toReal
          have hmul_eq :
              (fun x => HaarSystem.wavelet G F.toHaarSystem iw x * normalizedAlphaFunction G x)
                = (fun x => c * HaarSystem.wavelet G F.toHaarSystem iw x) := by
            funext x
            simp [normalizedAlphaFunction, c, mul_comm]
          rw [hmul_eq, MeasureTheory.integral_const_mul]
          rw [HaarSystem.integral_wavelet_eq_zero G F.toHaarSystem iw]
          simp
      | wavelet jw =>
          have hiw_jw : iw ≠ jw := by
            intro h
            apply hij
            cases h
            rfl
          simpa [FullHaarSystem.function]
            using HaarSystem.integral_mul_wavelet_eq_zero_of_ne G F.toHaarSystem iw jw hiw_jw

end UnbalancedHaarWavelet
