import UnbalancedHaarWavelet.Basic
import LaminarFamiliesMaximalBinaryTrees
import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.MeasureTheory.Function.AEEqOfIntegral

/-!
Foundational grid objects used by the rest of the project.

This file defines nested finite partitions and grids, then proves core helper
facts: nonemptiness of cells, child structure, and basic containment/disjoint
alternatives across levels.
-/

namespace UnbalancedHaarWavelet

variable {α : Type*} [MeasurableSpace α]

/-- A nested sequence of finite partitions of a measurable space -/
structure NestedFinitePartitionSequence where
  /-- Partitions indexed by natural numbers -/
  partitions : ℕ → Finset (Set α)
  /-- The first partition has exactly one element. -/
  first_partition_card_one : (partitions 0).card = 1
  /-- The unique element of the first partition is `α` (i.e. `Set.univ`). -/
  first_partition_eq_univ : partitions 0 = {Set.univ}
  /-- Each part is measurable -/
  measurable : ∀ n s, s ∈ partitions n → MeasurableSet s
  /-- every element of partition n+1 is contained in an element of the partition n -/
  nested : ∀ n s, s ∈ partitions (n + 1) → ∃ t, t ∈ partitions n ∧ s ⊆ t
  /-- father  is union of its children -/
  covering_father : ∀ n s, s ∈ partitions n → s ⊆ ⋃ t ∈ partitions (n + 1), t
  /-- Parts are pairwise disjoint -/
  disjoint : ∀ n s t, s ∈ partitions n → t ∈ partitions n → s ≠ t → Disjoint s t
  /-- Parts cover the space -/
  covering : ∀ n, (⋃ s ∈ partitions n, s) = Set.univ
  /-- The sigma algebra generated by the union of partitions -/
  generates : (⨆ n, MeasurableSpace.generateFrom (partitions n)) = ‹MeasurableSpace α›



structure Grid where
  /-- The measure on α -/
  μ : MeasureTheory.Measure α
  /-- The total mass is finite -/
  isFinite : MeasureTheory.IsFiniteMeasure μ
  /-- The nested sequence of finite partitions forming the grid -/
  grid : NestedFinitePartitionSequence (α := α)
  /-- Every elements of the partition has positive measure -/
  positive_measure : ∀ n s, s ∈ grid.partitions n → μ s > 0
  /-- Each child cell's measure smaller than its father -/
  measure_decrease : ∀ (n : ℕ) (s t : Set α),
      s ∈ grid.partitions (n + 1) → t ∈ grid.partitions n → s ⊆ t →
       μ s <  μ t




/-- Children of a cell `Q` at level `n`: cells in level `n+1` contained in `Q`. -/
def Grid.children (G : Grid (α := α)) (n : ℕ) (Q : Set α) : Set (Set α) :=
    {s | s ∈ G.grid.partitions (n + 1) ∧ s ⊆ Q}

/-- Finset version of `Grid.children`, obtained by filtering the next partition. -/
noncomputable def Grid.childrenFinset
    (G : Grid (α := α)) (n : ℕ) (Q : Set α) : Finset (Set α) :=
    by
        classical
        exact (G.grid.partitions (n + 1)).filter (fun s => s ⊆ Q)

    /-- Membership bridge between set-based and finset-based child collections. -/
lemma Grid.mem_childrenFinset_iff (G : Grid (α := α)) (n : ℕ) (Q s : Set α) :
        s ∈ G.childrenFinset n Q ↔ s ∈ G.children n Q := by
    classical
    simp [Grid.childrenFinset, Grid.children]

    /-- Iterated version of `nested`: jump directly from level `n + k` down to level `n`. -/
lemma NestedFinitePartitionSequence.nested_iterate
    (S : NestedFinitePartitionSequence (α := α))
    (n k : ℕ) (s : Set α) (hs : s ∈ S.partitions (n + k)) :
    ∃ t, t ∈ S.partitions n ∧ s ⊆ t := by
  induction k generalizing n s with
  | zero =>
      exact ⟨s, by simpa using hs, Set.Subset.rfl⟩
  | succ k ih =>
      have hs' : s ∈ S.partitions ((n + k) + 1) := by
        simpa [Nat.add_assoc] using hs
      obtain ⟨u, hu, hsu⟩ := S.nested (n + k) s hs'
      obtain ⟨t, ht, hut⟩ := ih n u hu
      exact ⟨t, ht, hsu.trans hut⟩

lemma Grid.partition_nonempty
  (G : Grid (α := α))
    (n : ℕ) (Q : Set α) (hQ : Q ∈ G.grid.partitions n) :
    Q.Nonempty := by
  by_contra hQ_empty
  simp only [Set.not_nonempty_iff_eq_empty] at hQ_empty
  have hμ0 : G.μ Q = 0 := by simp [hQ_empty]
  have hμpos : 0 < G.μ Q := G.positive_measure n Q hQ
  rw [hμ0] at hμpos
  exact absurd hμpos (lt_irrefl 0)

lemma Grid.partition_subset_or_disjoint_of_le
    (G : Grid (α := α))
    (n m : ℕ) (hnm : n ≤ m)
    (Q : Set α) (hQ : Q ∈ G.grid.partitions n)
    (P : Set α) (hP : P ∈ G.grid.partitions m) :
    P ⊆ Q ∨ Disjoint P Q := by
  classical
  have hP' : P ∈ G.grid.partitions (n + (m - n)) := by
    simpa [Nat.add_sub_of_le hnm] using hP
  obtain ⟨t, ht, hPt⟩ := G.grid.nested_iterate n (m - n) P hP'
  by_cases htQ : t = Q
  · left
    simpa [htQ] using hPt
  · right
    have htQ_disj : Disjoint t Q := G.grid.disjoint n t Q ht hQ htQ
    exact htQ_disj.mono_left hPt

lemma Grid.exists_child_containing_of_lt
    (G : Grid (α := α))
    (n m : ℕ) (hnm : n < m)
    (Q : Set α) (hQ : Q ∈ G.grid.partitions n)
    (P : Set α) (hP : P ∈ G.grid.partitions m)
    (hPQ : P ⊆ Q) :
    ∃ c, c ∈ G.children n Q ∧ P ⊆ c := by
  have hn1m : n + 1 ≤ m := by omega
  have hP' : P ∈ G.grid.partitions ((n + 1) + (m - (n + 1))) := by
    simpa [Nat.add_sub_of_le hn1m] using hP
  obtain ⟨c, hc, hPc⟩ := G.grid.nested_iterate (n + 1) (m - (n + 1)) P hP'
  obtain ⟨t, ht, hct⟩ := G.grid.nested n c hc
  have htQ : t = Q := by
    by_contra htQ_ne
    have htQ_disj : Disjoint t Q := G.grid.disjoint n t Q ht hQ htQ_ne
    obtain ⟨x, hxP⟩ := G.partition_nonempty m P hP
    have hx_t : x ∈ t := hct (hPc hxP)
    have hx_Q : x ∈ Q := hPQ hxP
    exact (Set.disjoint_left.mp htQ_disj hx_t hx_Q).elim
  refine ⟨c, ?_, hPc⟩
  exact ⟨hc, by simpa [htQ] using hct⟩


structure BinaryRefinementOfGrid (G : Grid (α := α)) [DecidableEq (Set α)] where
  tree : ∀ n (Q : Set α), Q ∈ G.grid.partitions n → BinaryTreeWithRootandTops (Set α)
  childs_are_children : ∀ n (Q : Set α) (hQ : Q ∈ G.grid.partitions n) (s : Set α),
      s ∈ (tree n Q hQ).Childs ↔ s ∈ G.children n Q
  tops_are_children : ∀ n (Q : Set α) (hQ : Q ∈ G.grid.partitions n) (s : Set α),
      s ∈ (tree n Q hQ).Tops ↔ s ∈ G.children n Q
  root_contains_children : ∀ n (Q : Set α) (hQ : Q ∈ G.grid.partitions n) (s : Set α),
      s ∈ G.children n Q → s ∈ Combinatorial_Support (tree n Q hQ).Root

/-- If a natural number is `< 2`, then it is either `0` or `1`. -/
lemma card_lt_two_eq_zero_or_one (k : ℕ) (hk : k < 2) : k = 0 ∨ k = 1 := by
  interval_cases k <;> simp_all

/-- Every cell in a Grid has at least one child in the next partition. -/
theorem Grid.children_card_ge_one
  (G : Grid (α := α)) (n : ℕ) (Q : Set α)
    (hQ : Q ∈ G.grid.partitions n) :
    (G.childrenFinset n Q).card ≥ 1 := by
  classical
  by_contra h
  push Not at h
  have h_card_zero : (G.childrenFinset n Q).card = 0 := by omega
  have h_empty : (G.childrenFinset n Q) = ∅ := Finset.card_eq_zero.mp h_card_zero
  -- By covering_father, Q is covered by the next partition level
  have h_covered : Q ⊆ ⋃ s ∈ G.grid.partitions (n + 1), s :=
    G.grid.covering_father n Q hQ
  -- Q must be nonempty (it's a partition element of a covering)
  have hQ_nonempty : Q.Nonempty := by
    by_contra h
    simp only [Set.not_nonempty_iff_eq_empty] at h
    have hμ0 : G.μ Q = 0 := by simp [h]
    have hμpos : 0 < G.μ Q := G.positive_measure n Q hQ
    rw [hμ0] at hμpos
    exact absurd hμpos (lt_irrefl 0)
  obtain ⟨x, hxQ⟩ := hQ_nonempty
  -- x is in some element of partition (n+1) by covering_father
  have hx_in_union : x ∈ ⋃ s ∈ G.grid.partitions (n + 1), s := h_covered hxQ
  simp only [Set.mem_iUnion, exists_prop] at hx_in_union
  obtain ⟨s, hs, hxs⟩ := hx_in_union
  -- By nested property, s is contained in some element t of partition n
  obtain ⟨t, ht, hs_sub_t⟩ := G.grid.nested n s hs
  -- Q and t are both in partition n. Since x ∈ Q and x ∈ s ⊆ t, we have Q = t
  have h_Q_eq_t : Q = t := by
    -- If Q ≠ t, they're disjoint by the disjoint property
    by_contra h_ne
    have h_disj : Disjoint (Q : Set α) (t : Set α) :=
      G.grid.disjoint n Q t hQ ht h_ne
    -- But x ∈ Q ∩ t, contradiction
    have hx_inter : x ∈ Q ∩ t := ⟨hxQ, hs_sub_t hxs⟩
    -- Disjoint means Q ⊓ t ≤ ⊥, which for sets means Q ∩ t ⊆ ∅
    have h_empty_inter : Q ∩ t ⊆ (∅ : Set α) := by
      have : (Q : Set α) ⊓ (t : Set α) = (⊥ : Set α) :=
        disjoint_iff.mp h_disj
      simpa [Set.le_eq_subset, Set.inf_eq_inter, Set.bot_eq_empty]
    have : x ∈ (∅ : Set α) := h_empty_inter hx_inter
    exact this.elim
  -- Therefore s ⊆ Q, so s is a child of Q
  have hs_sub_Q : s ⊆ Q := by rw [h_Q_eq_t]; exact hs_sub_t
  have hs_child : s ∈ G.childrenFinset n Q := by
    simp only [Grid.childrenFinset, Finset.mem_filter, hs, hs_sub_Q, and_true]
  -- This contradicts the empty assumption
  simp only [h_empty, Finset.notMem_empty] at hs_child




/-- If a cell does not have at least two children, then its children cardinal is `0` or `1`. -/
theorem Grid.children_card_cases_zero_or_one
  (G : Grid (α := α)) (n : ℕ) (Q : Set α)
    (h_not_ge_two : ¬ (G.childrenFinset n Q).card ≥ 2) :
    (G.childrenFinset n Q).card = 0 ∨ (G.childrenFinset n Q).card = 1 := by
  have hlt : (G.childrenFinset n Q).card < 2 := by omega
  exact card_lt_two_eq_zero_or_one _ hlt

/-- If `card(children) < 2`, then in fact `card(children) = 1` (never `0`). -/
theorem Grid.children_card_eq_one_of_not_ge_two
  (G : Grid (α := α)) (n : ℕ) (Q : Set α)
    (hQ : Q ∈ G.grid.partitions n)
    (h_not_ge_two : ¬ (G.childrenFinset n Q).card ≥ 2) :
    (G.childrenFinset n Q).card = 1 := by
  have h_cases :
      (G.childrenFinset n Q).card = 0 ∨ (G.childrenFinset n Q).card = 1 :=
    G.children_card_cases_zero_or_one n Q h_not_ge_two
  rcases h_cases with h_zero | h_one
  · have h_ge_one : (G.childrenFinset n Q).card ≥ 1 := G.children_card_ge_one n Q hQ
    omega
  · exact h_one


/-- Every point of a partition cell belongs to one of its children. -/
theorem Grid.covering_by_children
    (G : Grid (α := α))
    (n : ℕ) (Q : Set α) (hQ : Q ∈ G.grid.partitions n) :
    Q ⊆ ⋃ s ∈ G.children n Q, s := by
  classical
  intro x hxQ
  have hx_in_union : x ∈ ⋃ s ∈ G.grid.partitions (n + 1), s :=
    G.grid.covering_father n Q hQ hxQ
  simp only [Set.mem_iUnion, exists_prop] at hx_in_union
  obtain ⟨s, hs, hxs⟩ := hx_in_union
  obtain ⟨t, ht, hs_sub_t⟩ := G.grid.nested n s hs
  have h_Q_eq_t : Q = t := by
    by_contra h_ne
    have h_disj : Disjoint (Q : Set α) (t : Set α) :=
      G.grid.disjoint n Q t hQ ht h_ne
    have hx_inter : x ∈ Q ∩ t := ⟨hxQ, hs_sub_t hxs⟩
    have h_empty_inter : Q ∩ t ⊆ (∅ : Set α) := by
      have : (Q : Set α) ⊓ (t : Set α) = (⊥ : Set α) :=
        disjoint_iff.mp h_disj
      simpa [Set.le_eq_subset, Set.inf_eq_inter, Set.bot_eq_empty]
    exact (h_empty_inter hx_inter).elim
  have hs_sub_Q : s ⊆ Q := by
    rw [h_Q_eq_t]
    exact hs_sub_t
  have hs_child : s ∈ G.children n Q := ⟨hs, hs_sub_Q⟩
  exact Set.mem_iUnion.2 ⟨s, Set.mem_iUnion.2 ⟨hs_child, hxs⟩⟩


/-- If `Q` has exactly one child and children cover `Q`, then `Q` equals its only child. -/
theorem Grid.eq_only_child_of_children_card_eq_one
    (G : Grid (α := α))
    (n : ℕ) (Q : Set α)
    (hcard : (G.childrenFinset n Q).card = 1)
    (hQ : Q ∈ G.grid.partitions n) :
    ∃ s : Set α, s ∈ G.children n Q ∧ Q = s := by
  classical
  obtain ⟨s, hs_singleton⟩ := Finset.card_eq_one.mp hcard
  have hs_mem_finset : s ∈ G.childrenFinset n Q := by
    rw [hs_singleton]
    simp
  have hs_mem_child : s ∈ G.children n Q := (G.mem_childrenFinset_iff n Q s).1 hs_mem_finset
  have hs_sub_Q : s ⊆ Q := hs_mem_child.2
  have h_unique : ∀ t : Set α, t ∈ G.children n Q → t = s := by
    intro t ht_child
    have ht_fin : t ∈ G.childrenFinset n Q := (G.mem_childrenFinset_iff n Q t).2 ht_child
    have ht_single : t ∈ ({s} : Finset (Set α)) := by
      simpa [hs_singleton] using ht_fin
    simpa using ht_single
  have hQ_sub_s : Q ⊆ s := by
    intro x hxQ
    have hx_union : x ∈ ⋃ t ∈ G.children n Q, t :=
      G.covering_by_children n Q hQ hxQ
    rcases by simpa using hx_union with ⟨t, ht_child, hx_t⟩
    have ht_eq_s : t = s := h_unique t ht_child
    simpa [ht_eq_s] using hx_t
  refine ⟨s, hs_mem_child, Set.Subset.antisymm hQ_sub_s hs_sub_Q⟩

/-- Having exactly one child is impossible for a cell in a Grid,
    because child measures strictly decrease. -/
theorem Grid.not_children_card_eq_one
    (G : Grid (α := α))
    (n : ℕ) (Q : Set α) (hQ : Q ∈ G.grid.partitions n)
  :
    ¬ (G.childrenFinset n Q).card = 1 := by
  classical
  intro hcard
  obtain ⟨s, hs_child, hQ_eq_s⟩ :=
    G.eq_only_child_of_children_card_eq_one n Q hcard hQ
  have hs_part : s ∈ G.grid.partitions (n + 1) := hs_child.1
  have hs_sub : s ⊆ Q := hs_child.2
  have hμQ_lt_self : G.μ Q < G.μ Q := by
    simpa [hQ_eq_s] using G.measure_decrease n s Q hs_part hQ hs_sub
  exact (lt_irrefl (G.μ Q)) hμQ_lt_self

/-- Conclusion: every partition element has at least two children. -/
theorem Grid.all_partition_elements_have_two_children
    (G : Grid (α := α)) :
    ∀ n (Q : Set α), Q ∈ G.grid.partitions n → (G.childrenFinset n Q).card ≥ 2 := by
  classical
  intro n Q hQ
  by_contra h_not_ge_two
  have hcard1 : (G.childrenFinset n Q).card = 1 :=
    G.children_card_eq_one_of_not_ge_two n Q hQ h_not_ge_two
  have hnot1 : ¬ (G.childrenFinset n Q).card = 1 :=
    G.not_children_card_eq_one n Q hQ
  exact hnot1 hcard1

  end  UnbalancedHaarWavelet
