import UnbalancedHaarWavelet.Basic
import LaminarFamiliesMaximalBinaryTrees
import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.MeasureTheory.Function.AEEqOfIntegral
import UnbalancedHaarWavelet.GridDefinition
import UnbalancedHaarWavelet.HaarWaveletsDefinition
import UnbalancedHaarWavelet.HaarWaveletsInducedBinaryGrid
import UnbalancedHaarWavelet.HaarWaveletsLinearCombinations
import Mathlib.Probability.Martingale.Basic


namespace UnbalancedHaarWavelet

variable {α : Type*} [MeasurableSpace α]

/-- Partition-based filtration: at each deepness level n, we have the partition
    (collection of disjoint measurable sets) nodesAtDeepness G n. -/
noncomputable def HaarSystem.partitionFiltration
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    ℕ → Set (Set α) :=
  fun n ↦ H.nodesAtDeepness G n

/-- The sigma-algebra generated by the partition at deepness level n.
    This is the smallest sigma-algebra containing all partition elements at that level. -/
noncomputable def HaarSystem.sigmaalgebraAtDeepness
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    Set (Set α) :=
  {S | @MeasurableSet α
    (MeasurableSpace.generateFrom {T : Set α | T ∈ H.nodesAtDeepness G n}) S}

/-- Filtration of sigma-algebras generated by the partition sequence.
    ℱ_n = σ(nodesAtDeepness G n) is the sigma-algebra generated by all partition
    elements at deepness level n.

    This is a legacy set-valued shadow of the filtration. The actual Mathlib-compatible
    filtration object is `H.mathlibFiltration G` defined below. -/
noncomputable def HaarSystem.generatedFiltration
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    ℕ → Set (Set α) :=
  fun n ↦ H.sigmaalgebraAtDeepness G n

/-- The measurable space generated by the depth-`n` nodes of the induced binary grid. -/
abbrev HaarSystem.measurableSpaceAtDeepness
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) : MeasurableSpace α :=
  MeasurableSpace.generateFrom {S : Set α | S ∈ H.nodesAtDeepness G n}

/-- Every node of the induced binary grid is measurable in the ambient measurable space. -/
lemma HaarSystem.measurableSet_of_mem_nodesAtDeepness
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) {n : ℕ} {S : Set α}
    (hS : S ∈ H.nodesAtDeepness G n) :
    MeasurableSet S := by
  obtain ⟨_, _, _, _, _, hnode_split, _⟩ := H.binaryGrid_structure G
  obtain ⟨i, p, _, hp, _, _, _, _, _, h_union, _⟩ := hnode_split n S hS
  let T := H.binaryRefinement.tree i.level i.cell i.hcell
  have hp_childs : p.1 ⊆ T.Childs ∧ p.2 ⊆ T.Childs :=
    T.TreeStructureChilds p hp
  have hp1_part : ∀ s, s ∈ p.1 → s ∈ G.grid.partitions (i.level + 1) := by
    intro s hs
    exact (H.binaryRefinement.childs_are_children i.level i.cell i.hcell s).1
      (hp_childs.1 hs) |>.1
  have hp2_part : ∀ s, s ∈ p.2 → s ∈ G.grid.partitions (i.level + 1) := by
    intro s hs
    exact (H.binaryRefinement.childs_are_children i.level i.cell i.hcell s).1
      (hp_childs.2 hs) |>.1
  have hA_meas : MeasurableSet (branchSupport p.1) :=
    measurableSet_branchSupport_of_partition G i.level p.1 hp1_part
  have hB_meas : MeasurableSet (branchSupport p.2) :=
    measurableSet_branchSupport_of_partition G i.level p.2 hp2_part
  rw [h_union]
  exact hA_meas.union hB_meas

/-- The generated measurable spaces from the depth partitions form an increasing sequence. -/
lemma HaarSystem.measurableSpaceAtDeepness_mono
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    H.measurableSpaceAtDeepness G n ≤ H.measurableSpaceAtDeepness G (n + 1) := by
  obtain ⟨_, _, _, _, hchildren, _, _⟩ := H.binaryGrid_structure G
  refine MeasurableSpace.generateFrom_le ?_
  intro S hS
  obtain ⟨AB, _, hA_mem, hB_mem, _, _, h_union, _, _⟩ := hchildren n S hS
  rw [h_union]
  exact (MeasurableSpace.measurableSet_generateFrom hA_mem).union
    (MeasurableSpace.measurableSet_generateFrom hB_mem)

/-- The depth-`n` measurable space sits inside the ambient measurable space. -/
lemma HaarSystem.measurableSpaceAtDeepness_le
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    H.measurableSpaceAtDeepness G n ≤ ‹MeasurableSpace α› := by
  refine MeasurableSpace.generateFrom_le ?_
  intro S hS
  exact H.measurableSet_of_mem_nodesAtDeepness G hS

/-- The Mathlib-compatible filtration generated by the depth partitions.

This is the object that can be passed to `MeasureTheory.Martingale`,
`MeasureTheory.StronglyAdapted`, and related Mathlib APIs. -/
noncomputable def HaarSystem.mathlibFiltration
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) : MeasureTheory.Filtration ℕ ‹MeasurableSpace α› where
  seq n := H.measurableSpaceAtDeepness G n
  mono' := monotone_nat_of_le_succ (H.measurableSpaceAtDeepness_mono G)
  le' := H.measurableSpaceAtDeepness_le G

/-- Every node at depth `n` is measurable with respect to the Mathlib filtration at time `n`. -/
lemma HaarSystem.measurableSet_mathlibFiltration_of_mem
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) {S : Set α}
    (hS : S ∈ H.nodesAtDeepness G n) :
    @MeasurableSet α ((H.mathlibFiltration G) n) S := by
  simpa [HaarSystem.mathlibFiltration, HaarSystem.measurableSpaceAtDeepness] using
    (MeasurableSpace.measurableSet_generateFrom hS :
      @MeasurableSet α (MeasurableSpace.generateFrom {S : Set α | S ∈ H.nodesAtDeepness G n}) S)

/-- Each partition element at deepness level n is measurable. -/
lemma HaarSystem.measurable_partition_element
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) {S : Set α}
    (hS : S ∈ H.nodesAtDeepness G n) :
    S ∈ H.sigmaalgebraAtDeepness G n := by
  change @MeasurableSet α
    (MeasurableSpace.generateFrom {T : Set α | T ∈ H.nodesAtDeepness G n}) S
  exact MeasurableSpace.measurableSet_generateFrom hS

/-- The partition at deepness zero is {univ}. -/
lemma HaarSystem.partitionFiltration_zero_eq_singleton
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    H.partitionFiltration G 0 = {Set.univ} :=
  H.nodesAtDeepness_zero_eq_singleton G

/-- Monotonicity: the partition at deepness n+1 refines the partition at deepness n.
    This means every element of level n+1 is contained in some element of level n. -/
lemma HaarSystem.nodesAtDeepness_add_refines_lemma
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) {S : Set α} :
    S ∈ H.nodesAtDeepness G (n + 1) →
    ∃ T ∈ H.nodesAtDeepness G n, S ⊆ T :=
  by
    intro hS
    obtain ⟨_, _, _, hparent, _, _, _⟩ := H.binaryGrid_structure G
    simpa [Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using
      hparent (n + 1) S (Nat.succ_ne_zero n) hS

/-- The sigma-algebra at level n is contained in that at level n+1:
    ℱ_n ⊆ ℱ_{n+1}.
    This is because the partition at level n+1 is a refinement of that at level n. -/
lemma HaarSystem.sigmaalgebra_mono
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    H.sigmaalgebraAtDeepness G n ≤ H.sigmaalgebraAtDeepness G (n + 1) := by
  intro S hS
  change @MeasurableSet α
    (MeasurableSpace.generateFrom {T : Set α | T ∈ H.nodesAtDeepness G (n + 1)}) S
  change @MeasurableSet α
    (MeasurableSpace.generateFrom {T : Set α | T ∈ H.nodesAtDeepness G n}) S at hS
  exact (H.measurableSpaceAtDeepness_mono G n) S hS

/-- The legacy sigma-algebra at level `0` is the trivial sigma-algebra `{∅, univ}`. -/
lemma HaarSystem.sigmaalgebra_zero_is_trivial
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    H.sigmaalgebraAtDeepness G 0 = {∅, Set.univ} := by
  ext S
  rw [HaarSystem.sigmaalgebraAtDeepness, H.nodesAtDeepness_zero_eq_singleton G]
  change @MeasurableSet α (MeasurableSpace.generateFrom ({Set.univ} : Set (Set α))) S ↔
    S ∈ ({(∅ : Set α), Set.univ} : Set (Set α))
  rw [MeasurableSpace.generateFrom_singleton_univ, MeasurableSpace.measurableSet_bot_iff]
  simp [Set.mem_insert_iff, Set.mem_singleton_iff]

/-- The partition at each deepness level n consists of pairwise disjoint measurable sets. -/
lemma HaarSystem.nodesAtDeepness_pairwise_disjoint_or_equal
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    ∀ S₁ S₂, S₁ ∈ H.nodesAtDeepness G n → S₂ ∈ H.nodesAtDeepness G n →
      S₁ = S₂ ∨ Disjoint S₁ S₂ := by
  intro S₁ S₂ hS₁ hS₂
  rcases H.binaryGrid_structure G with ⟨_, hdisj, _, _, _, _, _⟩
  -- The structure theorem's second component gives pairwise disjointness or equality
  exact hdisj n S₁ S₂ hS₁ hS₂

/-- Elements of the partition at deepness n cover their union. -/
lemma HaarSystem.nodesAtDeepness_union_eq_of_subset
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) (S : Set α)
    (hS : S ∈ H.nodesAtDeepness G n) :
    0 < G.μ S :=
  H.measure_pos_of_mem_nodesAtDeepness G hS

/-- All partition elements are measurable in the generated filtration. -/
lemma HaarSystem.all_partition_elements_measurable
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    ∀ S ∈ H.nodesAtDeepness G n,
      S ∈ H.sigmaalgebraAtDeepness G n :=
  fun _ hS ↦ H.measurable_partition_element G n hS

/-- The filtration is increasing: ℱ_n ⊆ ℱ_{n+1}. -/
lemma HaarSystem.generatedFiltration_mono
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    H.generatedFiltration G n ≤ H.generatedFiltration G (n + 1) :=
  H.sigmaalgebra_mono G n

/-- The filtration is right-continuous in the index. -/
lemma HaarSystem.generatedFiltration_right_continuous
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    ∀ n : ℕ,
      H.generatedFiltration G n ≤ H.generatedFiltration G (n + 1) :=
  H.generatedFiltration_mono G



/-- The partition at deepness n is a σ-finite measurable partition of the space. -/
lemma HaarSystem.nodesAtDeepness_is_partition
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    (⋃ S ∈ H.nodesAtDeepness G n, S) = Set.univ ∧
    (∀ S₁ S₂, S₁ ∈ H.nodesAtDeepness G n → S₂ ∈ H.nodesAtDeepness G n → S₁ ≠ S₂ → Disjoint S₁ S₂) ∧
    (∀ S ∈ H.nodesAtDeepness G n, 0 < G.μ S) := by
  obtain ⟨_, hdisj, hcover, _, _, _, _⟩ := H.binaryGrid_structure G
  refine ⟨?_, ?_, ?_⟩
  · exact hcover n
  · intro S₁ S₂ hS₁ hS₂ hne
    rcases hdisj n S₁ S₂ hS₁ hS₂ with rfl | hSdisj
    · exact (hne rfl).elim
    · exact hSdisj
  · exact fun S hS ↦ H.measure_pos_of_mem_nodesAtDeepness G hS

/-- Each level of the induced binary partition has only finitely many nodes. -/
lemma HaarSystem.nodesAtDeepness_finite
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    (H.nodesAtDeepness G n).Finite := by
  have hfinite_nodes_all : ∀ m, (H.nodesAtDeepness G m).Finite := by
    intro m
    induction m with
    | zero =>
        simp [H.nodesAtDeepness_zero_eq_singleton G]
    | succ m ih =>
        classical
        obtain ⟨_, _, _, _, _, hnode_split, _⟩ := H.binaryGrid_structure G
        let parents : Finset (Set α) := ih.toFinset
        have hsplit_exists :
            ∀ S, S ∈ parents →
              ∃ AB : Set α × Set α,
                AB.1 ∈ H.nodesAtDeepness G (m + 1) ∧
                AB.2 ∈ H.nodesAtDeepness G (m + 1) ∧
                AB.1 ⊆ S ∧ AB.2 ⊆ S ∧
                S = AB.1 ∪ AB.2 := by
          intro S hS
          have hSnode : S ∈ H.nodesAtDeepness G m := ih.mem_toFinset.mp hS
          rcases hnode_split m S hSnode with
            ⟨_i, p, _hiS, _hp, _hS_eq, hA_mem, hB_mem, hA_sub, hB_sub, hAB_union, _hAB_disj⟩
          exact ⟨(UnbalancedHaarWavelet.branchSupport p.1,
            UnbalancedHaarWavelet.branchSupport p.2),
            hA_mem, hB_mem, hA_sub, hB_sub, hAB_union⟩
        let childPair := fun S hS => Classical.choose (hsplit_exists S hS)
        let children : Finset (Set α) :=
          parents.biUnion fun S =>
            if hS : S ∈ parents then
              let AB := childPair S hS
              ({AB.1, AB.2} : Finset (Set α))
            else
              ∅
        refine Set.Finite.subset children.finite_toSet ?_
        intro A hA
        have hA_nonempty : A.Nonempty := by
          by_contra hA_empty
          have hA_eq : A = ∅ := Set.not_nonempty_iff_eq_empty.mp hA_empty
          have hμ_pos : 0 < G.μ A := H.measure_pos_of_mem_nodesAtDeepness G hA
          simp [hA_eq] at hμ_pos
        obtain ⟨S, hS, hAS⟩ := H.nodesAtDeepness_add_refines_lemma G m hA
        have hSfin : S ∈ parents := ih.mem_toFinset.mpr hS
        have hABspec := Classical.choose_spec (hsplit_exists S hSfin)
        have hA_eq_left_or_right : A = (childPair S hSfin).1 ∨ A = (childPair S hSfin).2 := by
          rcases hABspec with ⟨hAB1, hAB2, _hAB1_sub, _hAB2_sub, hAB_union⟩
          have hleft :=
            H.nodesAtDeepness_eq_or_disjoint G (m + 1) A (childPair S hSfin).1 hA hAB1
          rcases hleft with hleft_eq | hleft_disj
          · exact Or.inl hleft_eq
          have hright :=
            H.nodesAtDeepness_eq_or_disjoint G (m + 1) A (childPair S hSfin).2 hA hAB2
          rcases hright with hright_eq | hright_disj
          · exact Or.inr hright_eq
          exfalso
          rcases hA_nonempty with ⟨x, hxA⟩
          have hxS : x ∈ S := hAS hxA
          have hxAB : x ∈ (childPair S hSfin).1 ∪ (childPair S hSfin).2 := by
            rw [hAB_union] at hxS
            exact hxS
          rcases hxAB with hxAB1 | hxAB2
          · exact (Set.disjoint_left.mp hleft_disj hxA hxAB1).elim
          · exact (Set.disjoint_left.mp hright_disj hxA hxAB2).elim
        refine Finset.mem_biUnion.mpr ⟨S, hSfin, ?_⟩
        have hmem_pair :
            A ∈ ({(childPair S hSfin).1, (childPair S hSfin).2} : Finset (Set α)) := by
          rcases hA_eq_left_or_right with hA_eq | hA_eq <;> simp [hA_eq]
        simpa [hSfin, childPair] using hmem_pair
  exact hfinite_nodes_all n

/-- A simple martingale can be constructed from the filtration by averaging a function
    over each partition element at level n. For each x, find the unique partition element
    at level n containing x, then return the average value of f on that element.

    This is the partition-model analogue of the conditional expectation E[f | ℱ_n],
    restricted to step functions on the cells of level n. -/
noncomputable def HaarSystem.martingaleFromPartition
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) : ℕ → α → ℝ :=
  fun n x ↦
    -- Find the unique partition element at level n containing x
    let hex : ∃ S, S ∈ H.nodesAtDeepness G n ∧ x ∈ S := by
      have hcover := (H.nodesAtDeepness_is_partition G n).1
      have hx : x ∈ ⋃ S ∈ H.nodesAtDeepness G n, S := hcover ▸ Set.mem_univ x
      simpa [Set.mem_iUnion, exists_prop] using hx
    let partition_elem : Set α := Classical.choose hex
    -- Return the average of f n over that partition element
    (∫ y in partition_elem, f y ∂G.μ) / (G.μ partition_elem).toReal

/-- If `x` belongs to a node `S` at deepness `n`, then `martingaleFromPartition` at time `n`
and point `x` is exactly the average of `f` over `S`. -/
lemma HaarSystem.martingaleFromPartition_eq_average_on_node
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ)
    {n : ℕ} {S : Set α} (hS : S ∈ H.nodesAtDeepness G n)
    {x : α} (hx : x ∈ S) :
    H.martingaleFromPartition G f n x = (∫ y in S, f y ∂G.μ) / (G.μ S).toReal := by
  classical
  let hex : ∃ T, T ∈ H.nodesAtDeepness G n ∧ x ∈ T := by
    have hcover := (H.nodesAtDeepness_is_partition G n).1
    have hx' : x ∈ ⋃ T ∈ H.nodesAtDeepness G n, T := hcover ▸ Set.mem_univ x
    simpa [Set.mem_iUnion, exists_prop] using hx'
  let T : Set α := Classical.choose hex
  have hT_mem : T ∈ H.nodesAtDeepness G n := (Classical.choose_spec hex).1
  have hxT : x ∈ T := (Classical.choose_spec hex).2
  have hTS : T = S := by
    by_contra hne
    have hdisj : Disjoint T S :=
      (H.nodesAtDeepness_is_partition G n).2.1 T S hT_mem hS hne
    exact (Set.disjoint_left.mp hdisj hxT hx).elim
  simp [HaarSystem.martingaleFromPartition, T, hTS]

/-- The sequence `martingaleFromPartition G H f` satisfies the one-step martingale identity on the
partition filtration: on each node `S` of level `n`, its value is the average of the next level
over `S`. -/
theorem HaarSystem.martingaleFromPartition_one_step
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ)
    (hf : MeasureTheory.Integrable f G.μ)
    {n : ℕ} {S : Set α} (hS : S ∈ H.nodesAtDeepness G n)
    {x : α} (hx : x ∈ S) :
    H.martingaleFromPartition G f n x =
      (∫ y in S, H.martingaleFromPartition G f (n + 1) y ∂G.μ) / (G.μ S).toReal := by
  classical
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  let M := H.martingaleFromPartition G f
  obtain ⟨-, -, -, -, -, hnode_split, -⟩ := H.binaryGrid_structure G
  obtain ⟨i, p, hiS, hp, hS_eq, hA_mem, hB_mem, hA_sub, hB_sub, h_union, h_disj⟩ :=
    hnode_split n S hS
  let A := UnbalancedHaarWavelet.branchSupport p.1
  let B := UnbalancedHaarWavelet.branchSupport p.2
  let T := H.binaryRefinement.tree i.level i.cell i.hcell
  have hp_childs : p.1 ⊆ T.Childs ∧ p.2 ⊆ T.Childs :=
    T.TreeStructureChilds p hp
  have hp1_part : ∀ s, s ∈ p.1 → s ∈ G.grid.partitions (i.level + 1) := by
    intro s hs
    exact (H.binaryRefinement.childs_are_children i.level i.cell i.hcell s).1
      (hp_childs.1 hs) |>.1
  have hp2_part : ∀ s, s ∈ p.2 → s ∈ G.grid.partitions (i.level + 1) := by
    intro s hs
    exact (H.binaryRefinement.childs_are_children i.level i.cell i.hcell s).1
      (hp_childs.2 hs) |>.1
  have hA_meas : MeasurableSet A := by
    dsimp [A]
    exact measurableSet_branchSupport_of_partition G i.level p.1 hp1_part
  have hB_meas : MeasurableSet B := by
    dsimp [B]
    exact measurableSet_branchSupport_of_partition G i.level p.2 hp2_part
  have hA_int : ∫ y in A, M (n + 1) y ∂G.μ = ∫ y in A, f y ∂G.μ := by
    have hμA_pos : 0 < G.μ A := H.measure_pos_of_mem_nodesAtDeepness G hA_mem
    have hμA_lt_top : G.μ A < ⊤ := MeasureTheory.measure_lt_top (μ := G.μ) A
    have hμA_toReal_pos : 0 < (G.μ A).toReal :=
      ENNReal.toReal_pos (ne_of_gt hμA_pos) hμA_lt_top.ne
    let avgA : ℝ := (∫ y in A, f y ∂G.μ) / (G.μ A).toReal
    have hconstA : Set.EqOn (fun y => M (n + 1) y) (fun _ => avgA) A := by
      intro y hy
      simpa [M, avgA] using H.martingaleFromPartition_eq_average_on_node G f hA_mem hy
    calc
      ∫ y in A, M (n + 1) y ∂G.μ = ∫ y in A, avgA ∂G.μ :=
        MeasureTheory.setIntegral_congr_fun hA_meas hconstA
      _ = ∫ y in A, f y ∂G.μ := by
        rw [MeasureTheory.setIntegral_const]
        change (G.μ A).toReal * ((∫ y in A, f y ∂G.μ) / (G.μ A).toReal) = ∫ y in A, f y ∂G.μ
        field_simp [hμA_toReal_pos.ne']
  have hB_int : ∫ y in B, M (n + 1) y ∂G.μ = ∫ y in B, f y ∂G.μ := by
    have hμB_pos : 0 < G.μ B := H.measure_pos_of_mem_nodesAtDeepness G hB_mem
    have hμB_lt_top : G.μ B < ⊤ := MeasureTheory.measure_lt_top (μ := G.μ) B
    have hμB_toReal_pos : 0 < (G.μ B).toReal :=
      ENNReal.toReal_pos (ne_of_gt hμB_pos) hμB_lt_top.ne
    let avgB : ℝ := (∫ y in B, f y ∂G.μ) / (G.μ B).toReal
    have hconstB : Set.EqOn (fun y => M (n + 1) y) (fun _ => avgB) B := by
      intro y hy
      simpa [M, avgB] using H.martingaleFromPartition_eq_average_on_node G f hB_mem hy
    calc
      ∫ y in B, M (n + 1) y ∂G.μ = ∫ y in B, avgB ∂G.μ :=
        MeasureTheory.setIntegral_congr_fun hB_meas hconstB
      _ = ∫ y in B, f y ∂G.μ := by
        rw [MeasureTheory.setIntegral_const]
        change (G.μ B).toReal * ((∫ y in B, f y ∂G.μ) / (G.μ B).toReal) = ∫ y in B, f y ∂G.μ
        field_simp [hμB_toReal_pos.ne']
  have hM_A_integrable : MeasureTheory.IntegrableOn (fun y => M (n + 1) y) A G.μ := by
    let avgA : ℝ := (∫ y in A, f y ∂G.μ) / (G.μ A).toReal
    have hconstA : Set.EqOn (fun y => M (n + 1) y) (fun _ => avgA) A := by
      intro y hy
      simpa [M, avgA] using H.martingaleFromPartition_eq_average_on_node G f hA_mem hy
    exact (MeasureTheory.integrableOn_congr_fun (μ := G.μ) (s := A) hconstA hA_meas).2
      (MeasureTheory.integrableOn_const (MeasureTheory.measure_lt_top (μ := G.μ) A).ne)
  have hM_B_integrable : MeasureTheory.IntegrableOn (fun y => M (n + 1) y) B G.μ := by
    let avgB : ℝ := (∫ y in B, f y ∂G.μ) / (G.μ B).toReal
    have hconstB : Set.EqOn (fun y => M (n + 1) y) (fun _ => avgB) B := by
      intro y hy
      simpa [M, avgB] using H.martingaleFromPartition_eq_average_on_node G f hB_mem hy
    exact (MeasureTheory.integrableOn_congr_fun (μ := G.μ) (s := B) hconstB hB_meas).2
      (MeasureTheory.integrableOn_const (MeasureTheory.measure_lt_top (μ := G.μ) B).ne)
  have hS_int : ∫ y in S, M (n + 1) y ∂G.μ = ∫ y in S, f y ∂G.μ := by
    rw [h_union]
    calc
      ∫ y in A ∪ B, M (n + 1) y ∂G.μ
          = ∫ y in A, M (n + 1) y ∂G.μ + ∫ y in B, M (n + 1) y ∂G.μ := by
              exact MeasureTheory.setIntegral_union h_disj hB_meas hM_A_integrable hM_B_integrable
      _ = ∫ y in A, f y ∂G.μ + ∫ y in B, f y ∂G.μ := by rw [hA_int, hB_int]
      _ = ∫ y in A ∪ B, f y ∂G.μ := by
            rw [MeasureTheory.setIntegral_union h_disj hB_meas hf.integrableOn hf.integrableOn]
  calc
    M n x = (∫ y in S, f y ∂G.μ) / (G.μ S).toReal :=
      H.martingaleFromPartition_eq_average_on_node G f hS hx
    _ = (∫ y in S, M (n + 1) y ∂G.μ) / (G.μ S).toReal := by rw [hS_int]

/-- The partition-average process is adapted to the filtration generated by the depth partitions. -/
lemma HaarSystem.martingaleFromPartition_adapted
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) :
    MeasureTheory.Adapted (H.mathlibFiltration G) (H.martingaleFromPartition G f) := by
  intro n
  classical
  let nodeType := {S : Set α // S ∈ H.nodesAtDeepness G n}
  have hfinite_nodes : (H.nodesAtDeepness G n).Finite := H.nodesAtDeepness_finite G n
  letI : Finite nodeType := hfinite_nodes.to_subtype
  letI : MeasurableSpace nodeType := ⊤
  let nodeSelector : α → nodeType := fun x =>
    let hex : ∃ S, S ∈ H.nodesAtDeepness G n ∧ x ∈ S := by
      have hcover := (H.nodesAtDeepness_is_partition G n).1
      have hx : x ∈ ⋃ S ∈ H.nodesAtDeepness G n, S := hcover ▸ Set.mem_univ x
      simpa [Set.mem_iUnion, exists_prop] using hx
    ⟨Classical.choose hex, (Classical.choose_spec hex).1⟩
  have hnodeSelector_mem : ∀ x, x ∈ (nodeSelector x).1 := by
    intro x
    dsimp [nodeSelector]
    exact (Classical.choose_spec
      (show ∃ S, S ∈ H.nodesAtDeepness G n ∧ x ∈ S by
        have hcover := (H.nodesAtDeepness_is_partition G n).1
        have hx : x ∈ ⋃ S ∈ H.nodesAtDeepness G n, S := hcover ▸ Set.mem_univ x
        simpa [Set.mem_iUnion, exists_prop] using hx)).2
  have hnodeSelector_eq_of_mem : ∀ {x : α}, (S : nodeType) → x ∈ S.1 → nodeSelector x = S := by
    intro x S hxS
    have hxT : x ∈ (nodeSelector x).1 := hnodeSelector_mem x
    rcases H.nodesAtDeepness_eq_or_disjoint G n (nodeSelector x).1 S.1
        (nodeSelector x).2 S.2 with hEq | hDisj
    · exact Subtype.ext hEq
    · exact (Set.disjoint_left.mp hDisj hxT hxS).elim
  have hselector_fiber :
      ∀ S : nodeType,
        @MeasurableSet α ((H.mathlibFiltration G) n) (nodeSelector ⁻¹' {S}) := by
    intro S
    have hpreimage : nodeSelector ⁻¹' {S} = S.1 := by
      ext x
      constructor
      · intro hx
        have hEq : nodeSelector x = S := by simpa using hx
        simpa [hEq] using hnodeSelector_mem x
      · intro hx
        change nodeSelector x ∈ ({S} : Set nodeType)
        simp [hnodeSelector_eq_of_mem S hx]
    rw [hpreimage]
    exact H.measurableSet_mathlibFiltration_of_mem G n S.2
  have hselector_meas :
      @Measurable α nodeType ((H.mathlibFiltration G) n) ⊤ nodeSelector := by
    exact @measurable_to_countable' nodeType α ⊤ inferInstance ((H.mathlibFiltration G) n)
      nodeSelector hselector_fiber
  let avgOnNode : nodeType → ℝ := fun S =>
    (∫ y in S.1, f y ∂G.μ) / (G.μ S.1).toReal
  have havg_meas : Measurable avgOnNode := Measurable.of_discrete
  have hcomp :
      @Measurable α ℝ ((H.mathlibFiltration G) n) _
        (fun x => avgOnNode (nodeSelector x)) :=
    havg_meas.comp hselector_meas
  have hrepr : (fun x => avgOnNode (nodeSelector x)) = H.martingaleFromPartition G f n := by
    funext x
    exact (H.martingaleFromPartition_eq_average_on_node G f (nodeSelector x).2
      (hnodeSelector_mem x)).symm
  rw [← hrepr]
  exact hcomp

/-- The partition-average process is strongly adapted to the Mathlib filtration. -/
lemma HaarSystem.martingaleFromPartition_stronglyAdapted
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) :
    MeasureTheory.StronglyAdapted (H.mathlibFiltration G) (H.martingaleFromPartition G f) := by
  exact (H.martingaleFromPartition_adapted G f).stronglyAdapted

/-- Each level of the partition-average process is integrable because it takes only finitely many
values on a finite-measure space. -/
lemma HaarSystem.martingaleFromPartition_integrable
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) (n : ℕ) :
    MeasureTheory.Integrable (H.martingaleFromPartition G f n) G.μ := by
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  classical
  let nodeType := {S : Set α // S ∈ H.nodesAtDeepness G n}
  have hfinite_nodes : (H.nodesAtDeepness G n).Finite := H.nodesAtDeepness_finite G n
  letI : Finite nodeType := hfinite_nodes.to_subtype
  letI : MeasurableSpace nodeType := ⊤
  let nodeSelector : α → nodeType := fun x =>
    let hex : ∃ S, S ∈ H.nodesAtDeepness G n ∧ x ∈ S := by
      have hcover := (H.nodesAtDeepness_is_partition G n).1
      have hx : x ∈ ⋃ S ∈ H.nodesAtDeepness G n, S := hcover ▸ Set.mem_univ x
      simpa [Set.mem_iUnion, exists_prop] using hx
    ⟨Classical.choose hex, (Classical.choose_spec hex).1⟩
  have hnodeSelector_mem : ∀ x, x ∈ (nodeSelector x).1 := by
    intro x
    dsimp [nodeSelector]
    exact (Classical.choose_spec
      (show ∃ S, S ∈ H.nodesAtDeepness G n ∧ x ∈ S by
        have hcover := (H.nodesAtDeepness_is_partition G n).1
        have hx : x ∈ ⋃ S ∈ H.nodesAtDeepness G n, S := hcover ▸ Set.mem_univ x
        simpa [Set.mem_iUnion, exists_prop] using hx)).2
  have hnodeSelector_eq_of_mem :
      ∀ {x : α}, (S : nodeType) → x ∈ S.1 → nodeSelector x = S := by
    intro x S hxS
    have hxT : x ∈ (nodeSelector x).1 := hnodeSelector_mem x
    rcases H.nodesAtDeepness_eq_or_disjoint G n (nodeSelector x).1 S.1
        (nodeSelector x).2 S.2 with hEq | hDisj
    · exact Subtype.ext hEq
    · exact (Set.disjoint_left.mp hDisj hxT hxS).elim
  have hpreimage : ∀ S : nodeType, nodeSelector ⁻¹' {S} = S.1 := by
    intro S
    ext x
    constructor
    · intro hx
      have hEq : nodeSelector x = S := by simpa using hx
      simpa [hEq] using hnodeSelector_mem x
    · intro hx
      change nodeSelector x ∈ ({S} : Set nodeType)
      simp [hnodeSelector_eq_of_mem S hx]
  have hselector_fiber : ∀ S : nodeType, MeasurableSet (nodeSelector ⁻¹' {S}) := by
    intro S
    rw [hpreimage S]
    exact H.measurableSet_of_mem_nodesAtDeepness G S.2
  have hselector_meas : Measurable nodeSelector :=
    measurable_to_countable' hselector_fiber
  let avgOnNode : nodeType → ℝ := fun S =>
    (∫ y in S.1, f y ∂G.μ) / (G.μ S.1).toReal
  have havg_meas : Measurable avgOnNode := Measurable.of_discrete
  have hmeas : Measurable (fun x => avgOnNode (nodeSelector x)) :=
    havg_meas.comp hselector_meas
  have hrepr : (fun x => avgOnNode (nodeSelector x)) = H.martingaleFromPartition G f n := by
    funext x
    exact (H.martingaleFromPartition_eq_average_on_node G f (nodeSelector x).2
      (hnodeSelector_mem x)).symm
  let C := max (Classical.choose (Finite.bddAbove_range fun S : nodeType => |avgOnNode S|)) 0
  have hC : ∀ S : nodeType, |avgOnNode S| ≤ C := by
    intro S
    refine le_trans ?_ (le_max_left _ _)
    exact Classical.choose_spec (Finite.bddAbove_range fun T : nodeType => |avgOnNode T|)
      ⟨S, rfl⟩
  have hbound : ∀ x, ‖avgOnNode (nodeSelector x)‖ ≤ C := by
    intro x
    simpa using hC (nodeSelector x)
  rw [← hrepr]
  exact MeasureTheory.Integrable.of_bound hmeas.aestronglyMeasurable C
    (Filter.Eventually.of_forall hbound)

/-- On every set measurable with respect to the depth-`n` filtration, the partition averages at
times `n` and `n + 1` have the same set integral. -/
lemma HaarSystem.martingaleFromPartition_setIntegral_eq_succ
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) (hf : MeasureTheory.Integrable f G.μ)
    (n : ℕ) {s : Set α}
  (hs : @MeasurableSet α ((H.mathlibFiltration G) n) s) :
    ∫ x in s, H.martingaleFromPartition G f n x ∂G.μ =
      ∫ x in s, H.martingaleFromPartition G f (n + 1) x ∂G.μ := by
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  classical
  let M := H.martingaleFromPartition G f
  let nodeType := {S : Set α // S ∈ H.nodesAtDeepness G n}
  have hfinite_nodes : (H.nodesAtDeepness G n).Finite := H.nodesAtDeepness_finite G n
  letI : Finite nodeType := hfinite_nodes.to_subtype
  letI : MeasurableSpace nodeType := ⊤
  let nodeSelector : α → nodeType := fun x =>
    let hex : ∃ S, S ∈ H.nodesAtDeepness G n ∧ x ∈ S := by
      have hcover := (H.nodesAtDeepness_is_partition G n).1
      have hx : x ∈ ⋃ S ∈ H.nodesAtDeepness G n, S := hcover ▸ Set.mem_univ x
      simpa [Set.mem_iUnion, exists_prop] using hx
    ⟨Classical.choose hex, (Classical.choose_spec hex).1⟩
  have hnodeSelector_mem : ∀ x, x ∈ (nodeSelector x).1 := by
    intro x
    dsimp [nodeSelector]
    exact (Classical.choose_spec
      (show ∃ S, S ∈ H.nodesAtDeepness G n ∧ x ∈ S by
        have hcover := (H.nodesAtDeepness_is_partition G n).1
        have hx : x ∈ ⋃ S ∈ H.nodesAtDeepness G n, S := hcover ▸ Set.mem_univ x
        simpa [Set.mem_iUnion, exists_prop] using hx)).2
  have hnodeSelector_eq_of_mem :
      ∀ {x : α}, (S : nodeType) → x ∈ S.1 → nodeSelector x = S := by
    intro x S hxS
    have hxT : x ∈ (nodeSelector x).1 := hnodeSelector_mem x
    rcases H.nodesAtDeepness_eq_or_disjoint G n (nodeSelector x).1 S.1
        (nodeSelector x).2 S.2 with hEq | hDisj
    · exact Subtype.ext hEq
    · exact (Set.disjoint_left.mp hDisj hxT hxS).elim
  have hpreimage : ∀ S : nodeType, nodeSelector ⁻¹' {S} = S.1 := by
    intro S
    ext x
    constructor
    · intro hx
      have hEq : nodeSelector x = S := by simpa using hx
      simpa [hEq] using hnodeSelector_mem x
    · intro hx
      change nodeSelector x ∈ ({S} : Set nodeType)
      simp [hnodeSelector_eq_of_mem S hx]
  have hselector_fiber :
      ∀ S : nodeType,
        @MeasurableSet α ((H.mathlibFiltration G) n) (nodeSelector ⁻¹' {S}) := by
    intro S
    rw [hpreimage S]
    exact H.measurableSet_mathlibFiltration_of_mem G n S.2
  have hselector_meas :
      @Measurable α nodeType ((H.mathlibFiltration G) n) ⊤ nodeSelector := by
    exact @measurable_to_countable' nodeType α ⊤ inferInstance ((H.mathlibFiltration G) n)
      nodeSelector hselector_fiber
  have hspace_left :
      H.measurableSpaceAtDeepness G n ≤ MeasurableSpace.comap nodeSelector ⊤ := by
    refine MeasurableSpace.generateFrom_le ?_
    intro S hS
    refine MeasurableSpace.measurableSet_comap.2 ?_
    refine ⟨{⟨S, hS⟩}, by simp, ?_⟩
    exact hpreimage ⟨S, hS⟩
  have hspace_right :
      MeasurableSpace.comap nodeSelector ⊤ ≤ H.measurableSpaceAtDeepness G n := by
    intro A hA
    rcases MeasurableSpace.measurableSet_comap.1 hA with ⟨U, hU, rfl⟩
    exact hselector_meas hU
  have hspace_eq : H.measurableSpaceAtDeepness G n = MeasurableSpace.comap nodeSelector ⊤ :=
    le_antisymm hspace_left hspace_right
  have hs_space : @MeasurableSet α (H.measurableSpaceAtDeepness G n) s := by
    simpa [HaarSystem.mathlibFiltration] using hs
  have hs_preimage :
      ∃ U : Set nodeType, @MeasurableSet nodeType ⊤ U ∧ nodeSelector ⁻¹' U = s := by
    have hs_raw : @MeasurableSet α (MeasurableSpace.comap nodeSelector ⊤) s :=
      hspace_left s hs_space
    exact MeasurableSpace.measurableSet_comap.1 hs_raw
  rcases hs_preimage with ⟨U, -, hU_eq⟩
  let t : Finset nodeType := Finset.univ.filter U
  have hs_union : s = ⋃ i ∈ t, i.1 := by
    ext x
    constructor
    · intro hx
      have hxU : nodeSelector x ∈ U := by
        change x ∈ nodeSelector ⁻¹' U
        simpa [hU_eq] using hx
      exact Set.mem_iUnion.2 ⟨nodeSelector x, Set.mem_iUnion.2 ⟨by simpa [t] using hxU,
        hnodeSelector_mem x⟩⟩
    · intro hx
      rcases Set.mem_iUnion.1 hx with ⟨i, hx⟩
      rcases Set.mem_iUnion.1 hx with ⟨hi, hxi⟩
      have hiU : i ∈ U := by simpa [t] using hi
      have hxU : nodeSelector x ∈ U := by
        simpa [hnodeSelector_eq_of_mem i hxi] using hiU
      rw [← hU_eq]
      exact hxU
  have hmeas_cells : ∀ i ∈ t, MeasurableSet (i.1) := by
    intro i hi
    exact H.measurableSet_of_mem_nodesAtDeepness G i.2
  have hdisj_cells : Set.Pairwise (↑t) (fun i j : nodeType => Disjoint i.1 j.1) := by
    intro i hi j hj hij
    rcases H.nodesAtDeepness_eq_or_disjoint G n i.1 j.1 i.2 j.2 with hEq | hDisj
    · exact (hij (Subtype.ext hEq)).elim
    · exact hDisj
  have hMn_int : ∀ i ∈ t, MeasureTheory.IntegrableOn (fun x => M n x) i.1 G.μ := by
    intro i hi
    exact (H.martingaleFromPartition_integrable G f n).integrableOn
  have hMn1_int : ∀ i ∈ t, MeasureTheory.IntegrableOn (fun x => M (n + 1) x) i.1 G.μ := by
    intro i hi
    exact (H.martingaleFromPartition_integrable G f (n + 1)).integrableOn
  have hcell_eq : ∀ i ∈ t,
      ∫ x in i.1, M n x ∂G.μ = ∫ x in i.1, M (n + 1) x ∂G.μ := by
    intro i hi
    have hμ_pos : 0 < G.μ i.1 := H.measure_pos_of_mem_nodesAtDeepness G i.2
    have hμ_lt_top : G.μ i.1 < ⊤ := MeasureTheory.measure_lt_top (μ := G.μ) i.1
    have hμ_toReal_pos : 0 < (G.μ i.1).toReal :=
      ENNReal.toReal_pos (ne_of_gt hμ_pos) hμ_lt_top.ne
    let avg : ℝ := (∫ y in i.1, M (n + 1) y ∂G.μ) / (G.μ i.1).toReal
    have hconst : Set.EqOn (fun y => M n y) (fun _ => avg) i.1 := by
      intro y hy
      simpa [M, avg] using H.martingaleFromPartition_one_step G f hf i.2 hy
    calc
      ∫ y in i.1, M n y ∂G.μ = ∫ y in i.1, avg ∂G.μ :=
        MeasureTheory.setIntegral_congr_fun (hmeas_cells i hi) hconst
      _ = ∫ y in i.1, M (n + 1) y ∂G.μ := by
        rw [MeasureTheory.setIntegral_const]
        change (G.μ i.1).toReal * ((∫ y in i.1, M (n + 1) y ∂G.μ) / (G.μ i.1).toReal)
            = ∫ y in i.1, M (n + 1) y ∂G.μ
        field_simp [hμ_toReal_pos.ne']
  rw [hs_union]
  calc
    ∫ x in ⋃ i ∈ t, i.1, M n x ∂G.μ = ∑ i ∈ t, ∫ x in i.1, M n x ∂G.μ := by
      exact MeasureTheory.integral_biUnion_finset t hmeas_cells hdisj_cells hMn_int
    _ = ∑ i ∈ t, ∫ x in i.1, M (n + 1) x ∂G.μ := by
      refine Finset.sum_congr rfl ?_
      intro i hi
      exact hcell_eq i hi
    _ = ∫ x in ⋃ i ∈ t, i.1, M (n + 1) x ∂G.μ := by
      symm
      exact MeasureTheory.integral_biUnion_finset t hmeas_cells hdisj_cells hMn1_int

/-- The partition-average process is a genuine Mathlib martingale. -/
theorem HaarSystem.martingaleFromPartition_martingale
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) (hf : MeasureTheory.Integrable f G.μ) :
    MeasureTheory.Martingale (H.martingaleFromPartition G f) (H.mathlibFiltration G) G.μ := by
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  refine MeasureTheory.martingale_of_setIntegral_eq_succ
    (H.martingaleFromPartition_stronglyAdapted G f)
    (H.martingaleFromPartition_integrable G f)
    ?_
  intro n s hs
  exact H.martingaleFromPartition_setIntegral_eq_succ G f hf n hs

/-- A canonical Haar index whose branch support is the node `P` at deepness `n`. -/
noncomputable def HaarSystem.indexOfNode
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (n : ℕ) (P : Set α) (hP : P ∈ H.nodesAtDeepness G n) : H.Index :=
  Classical.choose ((H.mem_nodesAtDeepness_iff G n P).1 hP)

lemma HaarSystem.indexOfNode_branchSupport
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (n : ℕ) (P : Set α) (hP : P ∈ H.nodesAtDeepness G n) :
    (H.indexOfNode G n P hP).branchSupport G H = P :=
  (Classical.choose_spec ((H.mem_nodesAtDeepness_iff G n P).1 hP)).1

lemma HaarSystem.indexOfNode_deepness
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (n : ℕ) (P : Set α) (hP : P ∈ H.nodesAtDeepness G n) :
    (H.indexOfNode G n P hP).deepness G H = n :=
  (Classical.choose_spec ((H.mem_nodesAtDeepness_iff G n P).1 hP)).2

/-- The coefficient of the orthogonal projection of `f` onto the span of the Haar wavelet
indexed by `i`. It is given by the usual formula
`⟪f, ψ_i⟫ / ‖ψ_i‖²`, written here as a quotient of integrals. -/
noncomputable def HaarSystem.projectionCoeff
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) (i : H.Index) : ℝ :=
  (∫ x, f x * H.wavelet G i x ∂G.μ) /
    (∫ x, H.wavelet G i x * H.wavelet G i x ∂G.μ)

/-- On a depth-`n` node `P`, the martingale increment is the projection of `f` onto the Haar
wavelet attached to the chosen branch index of `P`. -/
theorem HaarSystem.martingaleFromPartition_increment_eq_projectionCoeff_mul_wavelet
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) (hf : MeasureTheory.Integrable f G.μ)
    {n : ℕ} {P : Set α} (hP : P ∈ H.nodesAtDeepness G n)
    {x : α} (hx : x ∈ P) :
    let i := H.indexOfNode G n P hP
    H.martingaleFromPartition G f (n + 1) x - H.martingaleFromPartition G f n x =
      H.projectionCoeff G f i * H.wavelet G i x := by
  classical
  let i := H.indexOfNode G n P hP
  let A := UnbalancedHaarWavelet.branchSupport i.branch.1.1
  let B := UnbalancedHaarWavelet.branchSupport i.branch.1.2
  let M := H.martingaleFromPartition G f
  let μA : ℝ := (G.μ A).toReal
  let μB : ℝ := (G.μ B).toReal
  let μP : ℝ := (G.μ P).toReal
  let IA : ℝ := ∫ y in A, f y ∂G.μ
  let IB : ℝ := ∫ y in B, f y ∂G.μ
  have hiP : i.branchSupport G H = P := H.indexOfNode_branchSupport G n P hP
  have hiDeep : i.deepness G H = n := H.indexOfNode_deepness G n P hP
  have hA_mem : A ∈ H.nodesAtDeepness G (n + 1) := by
    simpa [i, A, hiDeep] using i.left_branchSupport_mem_nodesAtDeepness_succ G H
  have hB_mem : B ∈ H.nodesAtDeepness G (n + 1) := by
    simpa [i, B, hiDeep] using i.right_branchSupport_mem_nodesAtDeepness_succ G H
  have hA_meas : MeasurableSet A := H.measurableSet_of_mem_nodesAtDeepness G hA_mem
  have hB_meas : MeasurableSet B := H.measurableSet_of_mem_nodesAtDeepness G hB_mem
  have hAB : Disjoint A B := by
    simpa [i, A, B] using H.branchSupport_components_disjoint G i.branch
  have hP_eq_union : P = A ∪ B := by
    calc
      P = i.branchSupport G H := hiP.symm
      _ = haarBranchSupport i.branch.1 := rfl
      _ = A ∪ B := by simp [A, B, haarBranchSupport_eq_union_branchSupport]
  have hμA_pos : 0 < G.μ A := H.measure_pos_of_mem_nodesAtDeepness G hA_mem
  have hμB_pos : 0 < G.μ B := H.measure_pos_of_mem_nodesAtDeepness G hB_mem
  have hμP_pos : 0 < G.μ P := H.measure_pos_of_mem_nodesAtDeepness G hP
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  have hμA_ne : μA ≠ 0 := by
    dsimp [μA]
    exact ne_of_gt (ENNReal.toReal_pos (ne_of_gt hμA_pos) (MeasureTheory.measure_lt_top (μ := G.μ) A).ne)
  have hμB_ne : μB ≠ 0 := by
    dsimp [μB]
    exact ne_of_gt (ENNReal.toReal_pos (ne_of_gt hμB_pos) (MeasureTheory.measure_lt_top (μ := G.μ) B).ne)
  have hμP_ne : μP ≠ 0 := by
    dsimp [μP]
    exact ne_of_gt (ENNReal.toReal_pos (ne_of_gt hμP_pos) (MeasureTheory.measure_lt_top (μ := G.μ) P).ne)
  have hμP_eq : μP = μA + μB := by
    dsimp [μP, μA, μB]
    calc
      (G.μ P).toReal = (G.μ (A ∪ B)).toReal := by rw [hP_eq_union]
      _ = (G.μ A + G.μ B).toReal := by rw [MeasureTheory.measure_union hAB hB_meas]
      _ = (G.μ A).toReal + (G.μ B).toReal := by
        exact ENNReal.toReal_add (MeasureTheory.measure_lt_top (μ := G.μ) A).ne
          (MeasureTheory.measure_lt_top (μ := G.μ) B).ne
  have hM_n : M n x = (IA + IB) / μP := by
    have hP_int : ∫ y in P, f y ∂G.μ = IA + IB := by
      rw [hP_eq_union, MeasureTheory.setIntegral_union hAB hB_meas hf.integrableOn hf.integrableOn]
      rfl
    calc
      M n x = (∫ y in P, f y ∂G.μ) / (G.μ P).toReal :=
        H.martingaleFromPartition_eq_average_on_node G f hP hx
      _ = (IA + IB) / μP := by simp [IA, μP, hP_int]
  have hnum : ∫ y, f y * H.wavelet G i y ∂G.μ = IA / μA - IB / μB := by
    have hIntA : MeasureTheory.Integrable
        (fun y => Set.indicator A (fun z => f z * (1 / μA)) y) G.μ :=
      (hf.mul_const (1 / μA)).indicator hA_meas
    have hIntB : MeasureTheory.Integrable
        (fun y => Set.indicator B (fun z => f z * (1 / μB)) y) G.μ :=
      (hf.mul_const (1 / μB)).indicator hB_meas
    have hfun :
        (fun y => f y * H.wavelet G i y) =
          fun y => Set.indicator A (fun z => f z * (1 / μA)) y -
            Set.indicator B (fun z => f z * (1 / μB)) y := by
      funext y
      by_cases hyA : y ∈ A
      · have hyB : y ∉ B := by
          intro hyB
          exact (Set.disjoint_left.mp hAB hyA hyB).elim
        simp [HaarSystem.wavelet, H.haarWavelets_def, i, A, B, haarWavelet, hyA, hyB,
          μA, μB, mul_assoc]
      · by_cases hyB : y ∈ B
        · simp [HaarSystem.wavelet, H.haarWavelets_def, i, A, B, haarWavelet, hyA, hyB,
            μA, μB, mul_assoc]
        · simp [HaarSystem.wavelet, H.haarWavelets_def, i, A, B, haarWavelet, hyA, hyB,
            μA, μB, mul_assoc]
    rw [hfun, MeasureTheory.integral_sub hIntA hIntB]
    simp [IA, IB, hA_meas, hB_meas, μA, μB, div_eq_mul_inv, mul_comm, mul_left_comm, mul_assoc]
  have hden : ∫ y, H.wavelet G i y * H.wavelet G i y ∂G.μ = 1 / μA + 1 / μB := by
    have hIntA : MeasureTheory.Integrable
        (fun y => Set.indicator A (fun _ => (1 / μA) ^ 2) y) G.μ :=
      (MeasureTheory.integrable_const ((1 / μA) ^ 2)).indicator hA_meas
    have hIntB : MeasureTheory.Integrable
        (fun y => Set.indicator B (fun _ => (1 / μB) ^ 2) y) G.μ :=
      (MeasureTheory.integrable_const ((1 / μB) ^ 2)).indicator hB_meas
    have hfun :
        (fun y => H.wavelet G i y * H.wavelet G i y) =
          fun y => Set.indicator A (fun _ => (1 / μA) ^ 2) y +
            Set.indicator B (fun _ => (1 / μB) ^ 2) y := by
      funext y
      by_cases hyA : y ∈ A
      · have hyB : y ∉ B := by
          intro hyB
          exact (Set.disjoint_left.mp hAB hyA hyB).elim
        simp [HaarSystem.wavelet, H.haarWavelets_def, i, A, B, haarWavelet, hyA, hyB, μA, μB]
      · by_cases hyB : y ∈ B
        · simp [HaarSystem.wavelet, H.haarWavelets_def, i, A, B, haarWavelet, hyA, hyB, μA, μB]
        · simp [HaarSystem.wavelet, H.haarWavelets_def, i, A, B, haarWavelet, hyA, hyB, μA, μB]
    rw [hfun, MeasureTheory.integral_add hIntA hIntB]
    simp [hA_meas, hB_meas, μA, μB, div_eq_mul_inv, hμA_ne, hμB_ne]
    field_simp [hμA_ne, hμB_ne]
    ring
  have hcoeff : H.projectionCoeff G f i = (μB / μP) * (IA / μA) - (μA / μP) * (IB / μB) := by
    rw [HaarSystem.projectionCoeff, hnum, hden]
    field_simp [hμA_ne, hμB_ne, hμP_ne, hμP_eq]
    ring
  by_cases hxA : x ∈ A
  · have hxB : x ∉ B := by
      intro hxB
      exact (Set.disjoint_left.mp hAB hxA hxB).elim
    have hMx : M (n + 1) x = IA / μA := by
      calc
        M (n + 1) x = (∫ y in A, f y ∂G.μ) / (G.μ A).toReal :=
          H.martingaleFromPartition_eq_average_on_node G f hA_mem hxA
        _ = IA / μA := by simp [IA, μA]
    have hwave : H.wavelet G i x = 1 / μA := by
      simp [HaarSystem.wavelet, H.haarWavelets_def, i, A, B, haarWavelet, hxA, hxB, μA, μB]
    calc
      M (n + 1) x - M n x = IA / μA - (IA + IB) / μP := by rw [hMx, hM_n]
      _ = H.projectionCoeff G f i * H.wavelet G i x := by
        rw [hcoeff, hwave]
        field_simp [hμA_ne, hμB_ne, hμP_ne, hμP_eq]
        ring
  · have hxB : x ∈ B := by
      have hxUnion : x ∈ A ∪ B := by simpa [hP_eq_union] using hx
      exact hxUnion.resolve_left hxA
    have hMx : M (n + 1) x = IB / μB := by
      calc
        M (n + 1) x = (∫ y in B, f y ∂G.μ) / (G.μ B).toReal :=
          H.martingaleFromPartition_eq_average_on_node G f hB_mem hxB
        _ = IB / μB := by simp [IB, μB]
    have hwave : H.wavelet G i x = -(1 / μB) := by
      simp [HaarSystem.wavelet, H.haarWavelets_def, i, A, B, haarWavelet, hxA, hxB, μA, μB]
    calc
      M (n + 1) x - M n x = IB / μB - (IA + IB) / μP := by rw [hMx, hM_n]
      _ = H.projectionCoeff G f i * H.wavelet G i x := by
        rw [hcoeff, hwave]
        field_simp [hμA_ne, hμB_ne, hμP_ne, hμP_eq]
        ring

/-- There exists a filtration generated by the depth-`n` partitions and a martingale on that
filtration whose value on each partition cell is the average of `f` over that cell, and whose
increment on that cell is the orthogonal projection of `f` onto the corresponding Haar wavelet. -/
theorem HaarSystem.exists_filtration_martingale_average
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) (hf : MeasureTheory.Integrable f G.μ) :
    ∃ ℱ : MeasureTheory.Filtration ℕ ‹MeasurableSpace α›,
      (∀ n, ℱ n = MeasurableSpace.generateFrom {S : Set α | S ∈ H.nodesAtDeepness G n}) ∧
      ∃ F : ℕ → α → ℝ,
        MeasureTheory.Martingale F ℱ G.μ ∧
        ∀ n {P : Set α} (hP : P ∈ H.nodesAtDeepness G n) {x : α} (hx : x ∈ P),
          F n x = (∫ y in P, f y ∂G.μ) / (G.μ P).toReal ∧
          F (n + 1) x - F n x =
            H.projectionCoeff G f (H.indexOfNode G n P hP) *
              H.wavelet G (H.indexOfNode G n P hP) x
        := by
  refine ⟨H.mathlibFiltration G, ?_, H.martingaleFromPartition G f, ?_, ?_⟩
  · intro n
    rfl
  · exact H.martingaleFromPartition_martingale G f hf
  · intro n P hP x hx
    refine ⟨H.martingaleFromPartition_eq_average_on_node G f hP hx, ?_⟩
    simpa using H.martingaleFromPartition_increment_eq_projectionCoeff_mul_wavelet G f hf hP hx





end UnbalancedHaarWavelet
