import UnbalancedHaarWavelet.Basic
import LaminarFamiliesMaximalBinaryTrees
import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.MeasureTheory.Function.AEEqOfIntegral
import UnbalancedHaarWavelet.GridDefinition
import UnbalancedHaarWavelet.HaarWaveletsDefinition
import UnbalancedHaarWavelet.HaarWaveletsInducedBinaryGrid
import Mathlib.Probability.Martingale.Basic


namespace UnbalancedHaarWavelet

variable {α : Type*} [MeasurableSpace α]

/-- Partition-based filtration: at each deepness level n, we have the partition
    (collection of disjoint measurable sets) nodesAtDeepness G n. -/
noncomputable def HaarSystem.partitionFiltration
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    ℕ → Set (Set α) :=
  fun n ↦ H.nodesAtDeepness G n

/-- The sigma-algebra generated by the partition at deepness level n.
    This is the smallest sigma-algebra containing all partition elements at that level. -/
noncomputable def HaarSystem.sigmaalgebraAtDeepness
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (_H : HaarSystem (G := G)) (_n : ℕ) :
    Set (Set α) :=
  Set.univ  -- Placeholder: all sets assumed measurable

/-- Filtration of sigma-algebras generated by the partition sequence.
    ℱ_n = σ(nodesAtDeepness G n) is the sigma-algebra generated by all partition
    elements at deepness level n.

    This is a legacy set-valued shadow of the filtration. The actual Mathlib-compatible
    filtration object is `H.mathlibFiltration G` defined below. -/
noncomputable def HaarSystem.generatedFiltration
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    ℕ → Set (Set α) :=
  fun n ↦ H.sigmaalgebraAtDeepness G n

/-- The measurable space generated by the depth-`n` nodes of the induced binary grid. -/
abbrev HaarSystem.measurableSpaceAtDeepness
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) : MeasurableSpace α :=
  MeasurableSpace.generateFrom {S : Set α | S ∈ H.nodesAtDeepness G n}

/-- Every node of the induced binary grid is measurable in the ambient measurable space. -/
lemma HaarSystem.measurableSet_of_mem_nodesAtDeepness
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) {n : ℕ} {S : Set α}
    (hS : S ∈ H.nodesAtDeepness G n) :
    MeasurableSet S := by
  obtain ⟨_, _, _, _, _, hnode_split, _⟩ := H.binaryGrid_structure G
  obtain ⟨i, p, _, hp, _, _, _, _, _, h_union, _⟩ := hnode_split n S hS
  let T := H.binaryRefinement.tree i.level i.cell i.hcell
  have hp_childs : p.1 ⊆ T.Childs ∧ p.2 ⊆ T.Childs :=
    T.TreeStructureChilds p hp
  have hp1_part : ∀ s, s ∈ p.1 → s ∈ G.grid.partitions (i.level + 1) := by
    intro s hs
    exact (H.binaryRefinement.childs_are_children i.level i.cell i.hcell s).1
      (hp_childs.1 hs) |>.1
  have hp2_part : ∀ s, s ∈ p.2 → s ∈ G.grid.partitions (i.level + 1) := by
    intro s hs
    exact (H.binaryRefinement.childs_are_children i.level i.cell i.hcell s).1
      (hp_childs.2 hs) |>.1
  have hA_meas : MeasurableSet (branchSupport p.1) :=
    measurableSet_branchSupport_of_partition G i.level p.1 hp1_part
  have hB_meas : MeasurableSet (branchSupport p.2) :=
    measurableSet_branchSupport_of_partition G i.level p.2 hp2_part
  rw [h_union]
  exact hA_meas.union hB_meas

/-- The generated measurable spaces from the depth partitions form an increasing sequence. -/
lemma HaarSystem.measurableSpaceAtDeepness_mono
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    H.measurableSpaceAtDeepness G n ≤ H.measurableSpaceAtDeepness G (n + 1) := by
  obtain ⟨_, _, _, _, hchildren, _, _⟩ := H.binaryGrid_structure G
  refine MeasurableSpace.generateFrom_le ?_
  intro S hS
  obtain ⟨AB, _, hA_mem, hB_mem, _, _, h_union, _, _⟩ := hchildren n S hS
  rw [h_union]
  exact (MeasurableSpace.measurableSet_generateFrom hA_mem).union
    (MeasurableSpace.measurableSet_generateFrom hB_mem)

/-- The depth-`n` measurable space sits inside the ambient measurable space. -/
lemma HaarSystem.measurableSpaceAtDeepness_le
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    H.measurableSpaceAtDeepness G n ≤ ‹MeasurableSpace α› := by
  refine MeasurableSpace.generateFrom_le ?_
  intro S hS
  exact H.measurableSet_of_mem_nodesAtDeepness G hS

/-- The Mathlib-compatible filtration generated by the depth partitions.

This is the object that can be passed to `MeasureTheory.Martingale`,
`MeasureTheory.StronglyAdapted`, and related Mathlib APIs. -/
noncomputable def HaarSystem.mathlibFiltration
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) : MeasureTheory.Filtration ℕ ‹MeasurableSpace α› where
  seq n := H.measurableSpaceAtDeepness G n
  mono' := monotone_nat_of_le_succ (H.measurableSpaceAtDeepness_mono G)
  le' := H.measurableSpaceAtDeepness_le G

/-- Every node at depth `n` is measurable with respect to the Mathlib filtration at time `n`. -/
lemma HaarSystem.measurableSet_mathlibFiltration_of_mem
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) {S : Set α}
    (hS : S ∈ H.nodesAtDeepness G n) :
    @MeasurableSet α ((H.mathlibFiltration G) n) S := by
  simpa [HaarSystem.mathlibFiltration, HaarSystem.measurableSpaceAtDeepness] using
    (MeasurableSpace.measurableSet_generateFrom hS :
      @MeasurableSet α (MeasurableSpace.generateFrom {S : Set α | S ∈ H.nodesAtDeepness G n}) S)

/-- Each partition element at deepness level n is measurable. -/
lemma HaarSystem.measurable_partition_element
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) {S : Set α}
    (_hS : S ∈ H.nodesAtDeepness G n) :
    S ∈ H.sigmaalgebraAtDeepness G n := by
  exact Set.mem_univ S

/-- The partition at deepness zero is {univ}. -/
lemma HaarSystem.partitionFiltration_zero_eq_singleton
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    H.partitionFiltration G 0 = {Set.univ} :=
  H.nodesAtDeepness_zero_eq_singleton G

/-- Monotonicity: the partition at deepness n+1 refines the partition at deepness n.
    This means every element of level n+1 is contained in some element of level n. -/
lemma HaarSystem.nodesAtDeepness_add_refines_lemma
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) {S : Set α} :
    S ∈ H.nodesAtDeepness G (n + 1) →
    ∃ T ∈ H.nodesAtDeepness G n, S ⊆ T :=
  by
    intro hS
    obtain ⟨_, _, _, hparent, _, _, _⟩ := H.binaryGrid_structure G
    simpa [Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using
      hparent (n + 1) S (Nat.succ_ne_zero n) hS

/-- The sigma-algebra at level n is contained in that at level n+1:
    ℱ_n ⊆ ℱ_{n+1}.
    This is because the partition at level n+1 is a refinement of that at level n. -/
lemma HaarSystem.sigmaalgebra_mono
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    H.sigmaalgebraAtDeepness G n ≤ H.sigmaalgebraAtDeepness G (n + 1) := by
  exact le_refl _

/-- The base sigma-algebra at level 0 is {∅, univ}. -/
lemma HaarSystem.sigmaalgebra_zero_is_trivial
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    H.sigmaalgebraAtDeepness G 0 = {∅, Set.univ} := by
  sorry  -- Requires proper sigma-algebra definition (currently a placeholder)

/-- The partition at each deepness level n consists of pairwise disjoint measurable sets. -/
lemma HaarSystem.nodesAtDeepness_pairwise_disjoint_or_equal
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    ∀ S₁ S₂, S₁ ∈ H.nodesAtDeepness G n → S₂ ∈ H.nodesAtDeepness G n →
      S₁ = S₂ ∨ Disjoint S₁ S₂ := by
  intro S₁ S₂ hS₁ hS₂
  rcases H.binaryGrid_structure G with ⟨_, hdisj, _, _, _, _, _⟩
  -- The structure theorem's second component gives pairwise disjointness or equality
  exact hdisj n S₁ S₂ hS₁ hS₂

/-- Elements of the partition at deepness n cover their union. -/
lemma HaarSystem.nodesAtDeepness_union_eq_of_subset
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) (S : Set α)
    (hS : S ∈ H.nodesAtDeepness G n) :
    0 < G.μ S :=
  H.measure_pos_of_mem_nodesAtDeepness G hS

/-- All partition elements are measurable in the generated filtration. -/
lemma HaarSystem.all_partition_elements_measurable
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    ∀ S ∈ H.nodesAtDeepness G n,
      S ∈ H.sigmaalgebraAtDeepness G n :=
  fun _ hS ↦ H.measurable_partition_element G n hS

/-- The filtration is increasing: ℱ_n ⊆ ℱ_{n+1}. -/
lemma HaarSystem.generatedFiltration_mono
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    H.generatedFiltration G n ≤ H.generatedFiltration G (n + 1) :=
  H.sigmaalgebra_mono G n

/-- The filtration is right-continuous in the index. -/
lemma HaarSystem.generatedFiltration_right_continuous
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
    ∀ n : ℕ,
      H.generatedFiltration G n ≤ H.generatedFiltration G (n + 1) :=
  H.generatedFiltration_mono G



/-- The partition at deepness n is a σ-finite measurable partition of the space. -/
lemma HaarSystem.nodesAtDeepness_is_partition
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    (⋃ S ∈ H.nodesAtDeepness G n, S) = Set.univ ∧
    (∀ S₁ S₂, S₁ ∈ H.nodesAtDeepness G n → S₂ ∈ H.nodesAtDeepness G n → S₁ ≠ S₂ → Disjoint S₁ S₂) ∧
    (∀ S ∈ H.nodesAtDeepness G n, 0 < G.μ S) := by
  obtain ⟨_, hdisj, hcover, _, _, _, _⟩ := H.binaryGrid_structure G
  refine ⟨?_, ?_, ?_⟩
  · exact hcover n
  · intro S₁ S₂ hS₁ hS₂ hne
    rcases hdisj n S₁ S₂ hS₁ hS₂ with rfl | hSdisj
    · exact (hne rfl).elim
    · exact hSdisj
  · exact fun S hS ↦ H.measure_pos_of_mem_nodesAtDeepness G hS

/-- A simple martingale can be constructed from the filtration by averaging a function
    over each partition element at level n. For each x, find the unique partition element
    at level n containing x, then return the average value of f on that element.

    This is the partition-model analogue of the conditional expectation E[f | ℱ_n],
    restricted to step functions on the cells of level n. -/
noncomputable def HaarSystem.martingaleFromPartition
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ) : ℕ → α → ℝ :=
  fun n x ↦
    -- Find the unique partition element at level n containing x
    let hex : ∃ S, S ∈ H.nodesAtDeepness G n ∧ x ∈ S := by
      have hcover := (H.nodesAtDeepness_is_partition G n).1
      have hx : x ∈ ⋃ S ∈ H.nodesAtDeepness G n, S := hcover ▸ Set.mem_univ x
      simpa [Set.mem_iUnion, exists_prop] using hx
    let partition_elem : Set α := Classical.choose hex
    -- Return the average of f n over that partition element
    (∫ y in partition_elem, f y ∂G.μ) / (G.μ partition_elem).toReal

/-- If `x` belongs to a node `S` at deepness `n`, then `martingaleFromPartition` at time `n`
and point `x` is exactly the average of `f` over `S`. -/
lemma HaarSystem.martingaleFromPartition_eq_average_on_node
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ)
    {n : ℕ} {S : Set α} (hS : S ∈ H.nodesAtDeepness G n)
    {x : α} (hx : x ∈ S) :
    H.martingaleFromPartition G f n x = (∫ y in S, f y ∂G.μ) / (G.μ S).toReal := by
  classical
  let hex : ∃ T, T ∈ H.nodesAtDeepness G n ∧ x ∈ T := by
    have hcover := (H.nodesAtDeepness_is_partition G n).1
    have hx' : x ∈ ⋃ T ∈ H.nodesAtDeepness G n, T := hcover ▸ Set.mem_univ x
    simpa [Set.mem_iUnion, exists_prop] using hx'
  let T : Set α := Classical.choose hex
  have hT_mem : T ∈ H.nodesAtDeepness G n := (Classical.choose_spec hex).1
  have hxT : x ∈ T := (Classical.choose_spec hex).2
  have hTS : T = S := by
    by_contra hne
    have hdisj : Disjoint T S :=
      (H.nodesAtDeepness_is_partition G n).2.1 T S hT_mem hS hne
    exact (Set.disjoint_left.mp hdisj hxT hx).elim
  simp [HaarSystem.martingaleFromPartition, T, hTS]

/-- The sequence `martingaleFromPartition G H f` satisfies the one-step martingale identity on the
partition filtration: on each node `S` of level `n`, its value is the average of the next level
over `S`. -/
theorem HaarSystem.martingaleFromPartition_one_step
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G))
    (f : α → ℝ)
    (hf : MeasureTheory.Integrable f G.μ)
    {n : ℕ} {S : Set α} (hS : S ∈ H.nodesAtDeepness G n)
    {x : α} (hx : x ∈ S) :
    H.martingaleFromPartition G f n x =
      (∫ y in S, H.martingaleFromPartition G f (n + 1) y ∂G.μ) / (G.μ S).toReal := by
  classical
  letI : MeasureTheory.IsFiniteMeasure G.μ := G.isFinite
  let M := H.martingaleFromPartition G f
  obtain ⟨-, -, -, -, -, hnode_split, -⟩ := H.binaryGrid_structure G
  obtain ⟨i, p, hiS, hp, hS_eq, hA_mem, hB_mem, hA_sub, hB_sub, h_union, h_disj⟩ :=
    hnode_split n S hS
  let A := UnbalancedHaarWavelet.branchSupport p.1
  let B := UnbalancedHaarWavelet.branchSupport p.2
  let T := H.binaryRefinement.tree i.level i.cell i.hcell
  have hp_childs : p.1 ⊆ T.Childs ∧ p.2 ⊆ T.Childs :=
    T.TreeStructureChilds p hp
  have hp1_part : ∀ s, s ∈ p.1 → s ∈ G.grid.partitions (i.level + 1) := by
    intro s hs
    exact (H.binaryRefinement.childs_are_children i.level i.cell i.hcell s).1
      (hp_childs.1 hs) |>.1
  have hp2_part : ∀ s, s ∈ p.2 → s ∈ G.grid.partitions (i.level + 1) := by
    intro s hs
    exact (H.binaryRefinement.childs_are_children i.level i.cell i.hcell s).1
      (hp_childs.2 hs) |>.1
  have hA_meas : MeasurableSet A := by
    dsimp [A]
    exact measurableSet_branchSupport_of_partition G i.level p.1 hp1_part
  have hB_meas : MeasurableSet B := by
    dsimp [B]
    exact measurableSet_branchSupport_of_partition G i.level p.2 hp2_part
  have hA_int : ∫ y in A, M (n + 1) y ∂G.μ = ∫ y in A, f y ∂G.μ := by
    have hμA_pos : 0 < G.μ A := H.measure_pos_of_mem_nodesAtDeepness G hA_mem
    have hμA_lt_top : G.μ A < ⊤ := MeasureTheory.measure_lt_top (μ := G.μ) A
    have hμA_toReal_pos : 0 < (G.μ A).toReal :=
      ENNReal.toReal_pos (ne_of_gt hμA_pos) hμA_lt_top.ne
    let avgA : ℝ := (∫ y in A, f y ∂G.μ) / (G.μ A).toReal
    have hconstA : Set.EqOn (fun y => M (n + 1) y) (fun _ => avgA) A := by
      intro y hy
      simpa [M, avgA] using H.martingaleFromPartition_eq_average_on_node G f hA_mem hy
    calc
      ∫ y in A, M (n + 1) y ∂G.μ = ∫ y in A, avgA ∂G.μ :=
        MeasureTheory.setIntegral_congr_fun hA_meas hconstA
      _ = ∫ y in A, f y ∂G.μ := by
        rw [MeasureTheory.setIntegral_const]
        change (G.μ A).toReal * ((∫ y in A, f y ∂G.μ) / (G.μ A).toReal) = ∫ y in A, f y ∂G.μ
        field_simp [hμA_toReal_pos.ne']
  have hB_int : ∫ y in B, M (n + 1) y ∂G.μ = ∫ y in B, f y ∂G.μ := by
    have hμB_pos : 0 < G.μ B := H.measure_pos_of_mem_nodesAtDeepness G hB_mem
    have hμB_lt_top : G.μ B < ⊤ := MeasureTheory.measure_lt_top (μ := G.μ) B
    have hμB_toReal_pos : 0 < (G.μ B).toReal :=
      ENNReal.toReal_pos (ne_of_gt hμB_pos) hμB_lt_top.ne
    let avgB : ℝ := (∫ y in B, f y ∂G.μ) / (G.μ B).toReal
    have hconstB : Set.EqOn (fun y => M (n + 1) y) (fun _ => avgB) B := by
      intro y hy
      simpa [M, avgB] using H.martingaleFromPartition_eq_average_on_node G f hB_mem hy
    calc
      ∫ y in B, M (n + 1) y ∂G.μ = ∫ y in B, avgB ∂G.μ :=
        MeasureTheory.setIntegral_congr_fun hB_meas hconstB
      _ = ∫ y in B, f y ∂G.μ := by
        rw [MeasureTheory.setIntegral_const]
        change (G.μ B).toReal * ((∫ y in B, f y ∂G.μ) / (G.μ B).toReal) = ∫ y in B, f y ∂G.μ
        field_simp [hμB_toReal_pos.ne']
  have hM_A_integrable : MeasureTheory.IntegrableOn (fun y => M (n + 1) y) A G.μ := by
    let avgA : ℝ := (∫ y in A, f y ∂G.μ) / (G.μ A).toReal
    have hconstA : Set.EqOn (fun y => M (n + 1) y) (fun _ => avgA) A := by
      intro y hy
      simpa [M, avgA] using H.martingaleFromPartition_eq_average_on_node G f hA_mem hy
    exact (MeasureTheory.integrableOn_congr_fun (μ := G.μ) (s := A) hconstA hA_meas).2
      (MeasureTheory.integrableOn_const (MeasureTheory.measure_lt_top (μ := G.μ) A).ne)
  have hM_B_integrable : MeasureTheory.IntegrableOn (fun y => M (n + 1) y) B G.μ := by
    let avgB : ℝ := (∫ y in B, f y ∂G.μ) / (G.μ B).toReal
    have hconstB : Set.EqOn (fun y => M (n + 1) y) (fun _ => avgB) B := by
      intro y hy
      simpa [M, avgB] using H.martingaleFromPartition_eq_average_on_node G f hB_mem hy
    exact (MeasureTheory.integrableOn_congr_fun (μ := G.μ) (s := B) hconstB hB_meas).2
      (MeasureTheory.integrableOn_const (MeasureTheory.measure_lt_top (μ := G.μ) B).ne)
  have hS_int : ∫ y in S, M (n + 1) y ∂G.μ = ∫ y in S, f y ∂G.μ := by
    rw [h_union]
    calc
      ∫ y in A ∪ B, M (n + 1) y ∂G.μ
          = ∫ y in A, M (n + 1) y ∂G.μ + ∫ y in B, M (n + 1) y ∂G.μ := by
              exact MeasureTheory.setIntegral_union h_disj hB_meas hM_A_integrable hM_B_integrable
      _ = ∫ y in A, f y ∂G.μ + ∫ y in B, f y ∂G.μ := by rw [hA_int, hB_int]
      _ = ∫ y in A ∪ B, f y ∂G.μ := by
            rw [MeasureTheory.setIntegral_union h_disj hB_meas hf.integrableOn hf.integrableOn]
  calc
    M n x = (∫ y in S, f y ∂G.μ) / (G.μ S).toReal :=
      H.martingaleFromPartition_eq_average_on_node G f hS hx
    _ = (∫ y in S, M (n + 1) y ∂G.μ) / (G.μ S).toReal := by rw [hS_int]

/-- The filtration restricts to a σ-finite measure-preserving structure. -/
lemma HaarSystem.filtraton_preserves_measure
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) (n : ℕ) :
    ∀ S, S ∈ H.nodesAtDeepness G n →
      ∃ T, T ∈ H.nodesAtDeepness G (n + 1) ∧ T ⊆ S := by
  intro S hS
  -- By the structure theorem, every node has children at the next level; take the left one.
  obtain ⟨_, _, _, _, _, hnode_split, _⟩ := H.binaryGrid_structure G
  obtain ⟨_, p, _, _, _, hA_mem, _, hA_sub, _, _, _⟩ := hnode_split n S hS
  exact ⟨UnbalancedHaarWavelet.branchSupport p.1, hA_mem, hA_sub⟩

/-- Summary: The filtration generated by the partition sequence of a Haar system
    is an increasing sequence of σ-algebras where each level n has the partition
    nodesAtDeepness G n as generators.

    Properties:
    - ℱ₀ = {∅, univ} is the trivial σ-algebra
    - ℱₙ ⊆ ℱₙ₊₁ (increasing)
    - Each partition element at level n is positive measure and measurable
    - The partitions refine: each element at level n+1 is contained in some element at level n
    - All elements are related to Haar branch supports via the binary grid structure
-/
theorem HaarSystem.filtration_summary
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
  (-- Base case: level 0 is trivial
    H.nodesAtDeepness G 0 = {Set.univ}) ∧
  (-- Monotonicity: partition refines at each step
    ∀ n S, S ∈ H.nodesAtDeepness G (n + 1) →
      ∃ T ∈ H.nodesAtDeepness G n, S ⊆ T) ∧
  (-- Sigma-algebra monotonicity
    ∀ n, H.sigmaalgebraAtDeepness G n ≤ H.sigmaalgebraAtDeepness G (n + 1)) ∧
  (-- All partition elements have positive measure
    ∀ n S, S ∈ H.nodesAtDeepness G n → 0 < G.μ S) ∧
  (-- All partition elements are measurable in their respective σ-algebra
    ∀ n S, S ∈ H.nodesAtDeepness G n → S ∈ H.sigmaalgebraAtDeepness G n) :=
  ⟨H.nodesAtDeepness_zero_eq_singleton G,
   H.nodesAtDeepness_add_refines_lemma G,
   H.sigmaalgebra_mono G,
   fun _ _ hS ↦ H.measure_pos_of_mem_nodesAtDeepness G hS,
   fun n _ hS ↦ H.measurable_partition_element G n hS⟩

/-- Connection to binary grid structure: The filtration is derived from the
    characterization of the partition sequence provided by HaarSystem.binaryGrid_structure.

    The binaryGrid_structure theorem states that:
    1. The partition at level 0 is {univ}
    2. Partitions at the same level are pairwise disjoint or equal
    3. Each partition element at level n has exactly two children at level n+1
    4. Every branch support appears in some partition
    5. Every partition element is a branch support

    The filtration then consists of the σ-algebras generated by these partitions at each level.
-/
theorem HaarSystem.filtration_from_binary_grid_structure
    (G : Grid (α := α)) [DecidableEq (Set α)]
    (H : HaarSystem (G := G)) :
  (-- The partition sequence defines our filtration
    H.partitionFiltration G 0 = {Set.univ}) ∧
  (-- Elements at each level partition the space
    ∀ n, Pairwise (fun S₁ S₂ : H.nodesAtDeepness G n =>
      S₁.val = S₂.val ∨ Disjoint S₁.val S₂.val)) :=
  by
    constructor
    · exact H.partitionFiltration_zero_eq_singleton G
    · intro n S₁ S₂ _hne
      exact H.nodesAtDeepness_pairwise_disjoint_or_equal G n S₁.val S₂.val S₁.property S₂.property



end UnbalancedHaarWavelet
